### ISSUE TITLE
GPG signature verification fails running ./streisand

### ISSUE THREAD

**Issue by jsieczko** [jlund/streisand#819] opened 2017-07-20 02:05 UTC
### Expected behavior:
TASK [download-and-verify : Register GPG signature verification results] 
ok: ....

### Actual Behavior:
TASK [download-and-verify : Register GPG signature verification results] ***************************************************
fatal: [34.230.177.167]: FAILED! => {"changed": true, "cmd": "for file in *.asc; do gpg --verify $file; done", "delta": "0:00:00.031929", "end": "2017-07-20 01:53:34.987383", "failed": true, "rc": 2, "start": "2017-07-20 01:53:34.955454", "stderr": "gpg: assuming signed data in `openvpn-install-latest-stable.exe'\ngpg: Signature made Wed 22 Mar 2017 04:51:46 PM UTC using RSA key ID 40864578\ngpg: Can't check signature: public key not found\ngpg: assuming signed data in `openvpn-latest-stable.tar.gz'\ngpg: Signature made Wed 22 Mar 2017 03:35:16 PM UTC using RSA key ID 40864578\ngpg: Can't check signature: public key not found", "stderr_lines": ["gpg: assuming signed data in `openvpn-install-latest-stable.exe'", "gpg: Signature made Wed 22 Mar 2017 04:51:46 PM UTC using RSA key ID 40864578", "gpg: Can't check signature: public key not found", "gpg: assuming signed data in `openvpn-latest-stable.tar.gz'", "gpg: Signature made Wed 22 Mar 2017 03:35:16 PM UTC using RSA key ID 40864578", "gpg: Can't check signature: public key not found"], "stdout": "", "stdout_lines": []}

TASK [streisand-mirror : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***
Pausing for 20 seconds

### Steps to Reproduce:
1. ./streisand

### Additional Details:
Everything succeeded except GPG key verification

PLAY RECAP *****************************************************************************************************************
34.230.177.167             : ok=346  changed=304  unreachable=0    failed=1   
localhost                  : ok=20   changed=11   unreachable=0    failed=0   

##### *Target Cloud Provider:*
Amazon AWS
##### *Operating System of target host:*
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
##### *Operating System of client:*
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
##### *Version of Ansible, using `ansible --version` :*
$ ansible --version
ansible 2.3.1.0
  config file = /Users/joes/streisand/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]

**Comment by alimakki** [comment] 2017-07-20 11:26
@jsieczko, this should have been fixed in #812.

Do you have the latest master?

**Comment by cpu** [comment] 2017-07-23 14:32
@jsieczko Gentle bump on [Ali's question above](https://github.com/jlund/streisand/issues/819#issuecomment-316675326). What is the output from `git rev-parse HEAD` in the Streisand directory that you created this server from?

**Comment by jsieczko** [comment] 2017-07-24 01:11
Sorry for the delay.... I ran streisand shortly after I downloaded it (i.e. git clone https://github.com/jlund/streisand.git). 

$ git rev-parse HEAD
b946974596c3af64a5099920cc5ff42268388240

**Comment by jsieczko** [comment] 2017-07-24 01:11
$ git rev-parse HEAD
b946974596c3af64a5099920cc5ff42268388240

**Comment by jsieczko** [comment] 2017-07-24 01:12
$ git rev-parse HEAD
"b946974596c3af64a5099920cc5ff42268388240"

**Comment by cpu** [comment] 2017-07-24 13:40
Hi @jsieczko,

You're clone at b946974 is missing the fix from #812 that Ali mentioned: 57d5219ca0730796618801e1e11938ca2630355b.

You should run `git pull` in the directory of your Streisand clone & re-run the provisioning. At that point the GPG signature verification for the OpenVPN client won't fail. 

I'm going to close this issue since the root cause was already addressed. Thanks!


--

**Closed by cpu** 2017-07-24 13:40 UTC
Labels: area/mirror, area/openvpn, status/information-needed
