### ISSUE TITLE
WireGuard does not seem to work with Linode.

### ISSUE THREAD

**Issue by ddvzlnz** [jlund/streisand#543] opened 2017-03-20 16:59 UTC
Works fine on DOcean and bare metal.  All other connections work ok on Linode, wireguard just won't connect.  Must be something Linode is blocking.  I tried Singapore and Atlanta.

**Comment by zx2c4** [comment] 2017-03-30 00:09
https://github.com/jlund/streisand/issues/500

**Comment by cpu** [comment] 2017-04-07 01:16
Closing as a duplicate of #500

**Closed by cpu** 2017-04-07 01:16 UTC
Labels: area/wireguard, kind/question, provider/linode
