### ISSUE TITLE
setup failure on aws

### ISSUE THREAD

**Issue by go-gitter** [jlund/streisand#617] opened 2017-04-17 03:07 UTC
hello,

I am running into problems when connecting to my EC2 instance - this is similar to issue #560 reported by @ausoro. I added a comment in #560 but this issue is closed so submitting mine as a new issue. Appreciate any inputs/help.

< TASK [Wait for cloud-init to complete] >
fatal: [52.40.104.243]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '52.40.104.243' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}
to retry, use: --limit @/home/user1/streisand/playbooks/amazon.retry
< PLAY RECAP >

52.40.104.243 : ok=0 changed=0 unreachable=1 failed=0
localhost : ok=17 changed=9 unreachable=0 failed=0

@blizzbhaller - "Change the default ip there to the ip of your instance." - by IP of your instance, I am guessing you meant the IP of the EC2 instance, please let me know if it should be something else.

@ausoro - "10.1.1.1 ansible_user=ubuntu" - the IP 10.1.1.1 is that of your EC2?

**Comment by nickolasclarke** [comment] 2017-04-17 03:26
@go-gitter is this failing at the beginning of the set up process? It seems like there is an issue with the key that you've specified for connecting over SSH. `Permission denied (publickey)`. 

Can you spin up an micro instance manually and try to connect over SSH using the same key you specified in the setup for Streisand?

**Comment by blizzbhaller** [comment] 2017-04-18 10:10
Yes, I meant the IP of your EC2 instance. Make sure you indicate the correct path for your pem file associated with your ec2 instance as well under:
ansible_ssh_private_key_file="your pem key and the path to it"

**Comment by go-gitter** [comment] 2017-04-19 22:37
@nickolasclarke: thanks for your response. I am traveling and couldnt respond any sooner. 

The streisand script ran ok until it hit the permission issue

/ TASK [genesis-amazon : Create the in-memory inventory \
\ group]                                                /
 -------------------------------------------------------
changed: [localhost]
 _______________________________________________________
/ TASK [genesis-amazon : Set the streisand_ipv4_address \
\ variable]                                             /
 -------------------------------------------------------
ok: [localhost]
 ______________________________________________________
/ TASK [genesis-amazon : Set the streisand_server_name \
\ variable]                                            

ok: [localhost]
 _________________________________________________________
/ TASK [genesis-amazon : New EC2 servers are occasionally \
| slow to process incoming SSH connections even after the |
\ OpenSSH daemon has started up. Pause for 90 seconds.]   /
 ---------------------------------------------------------

Pausing for 90 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]
 _________________________________

 ________________________________________
< TASK [Wait for cloud-init to complete] >
 ----------------------------------------

fatal: [52.42.173.13]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '52.42.173.13' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}

I tried to ssh into the EC2 instance like you suggested and got the same permission denied included below is the output, appreciate if you can help me make sense out of it.

testo@hpc1 ~/streisand $ ssh -v -i streisand-vpn.pem ec2-user@ec2-52-42-173-13.us-west-2.compute.amazonaws.com
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to ec2-52-42-173-13.us-west-2.compute.amazonaws.com [52.42.173.13] port 22.
debug1: Connection established.
debug1: identity file streisand-vpn.pem type -1
debug1: identity file streisand-vpn.pem-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1 pat OpenSSH* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha1-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha1-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 40:f5:ce:b3:56:7b:8b:d1:9d:5d:9b:ee:da:e3:52:4a
debug1: Host 'ec2-52-42-173-13.us-west-2.compute.amazonaws.com' is known and matches the ECDSA host key.
debug1: Found key in /home/testo/.ssh/known_hosts:5
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: streisand-vpn.pem
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type RSA
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
Permission denied (publickey).

@blizzbhaller - thank you, i verified the entries after reading your response and they are.

I understand its a problem with the authentication but not sure what the fix should be

**Comment by nickolasclarke** [comment] 2017-04-20 04:49
I'm not familiar with how AWS manages SSH keys off the top of my head, but this is certainly seems to be an issue with the SSH keypair you are trying to use not matching up with what is available on the AWS instance. 

A quick cursory look at the `genesis-amazon` role in the streistand playbooks suggests that Streisand adds a ssh-key to AWS with the name `streisand-ssh`, populated with the value the default key that has been generated on the machine that is running the streisand script, namely: `~/.ssh/id_rsa.pub`. this pub key would then be added to  ` ~/.ssh/authorized_keys` on the streisand host on AWS. Streisand would then attempt to use that key pair to connect once the host is online and reachable. However, for whatever reason this is failing. 

First step would be to be sure you have a keypair generated on your client that can be used to populate the `streisand-ssh` key

**Comment by cpu** [comment] 2017-05-24 00:06
@go-gitter Are you still having trouble or was @nickolasclarke's information above enough? I'm going to close this issue shortly since it appears to be resolved.

**Comment by cpu** [comment] 2017-06-08 15:17
I have been able to provision EC2 instances successfully with the code in master. Since this issue is stale and I can't reproduce I'm going to close it. Thanks all!

**Closed by cpu** 2017-06-08 15:17 UTC
Labels: area/provisioning, area/ssh, kind/question, provider/amazon, status/information-needed
