### ISSUE TITLE
shadowsocks not working

### ISSUE THREAD

**Issue by nakamin** [jlund/streisand#580] opened 2017-04-07 22:07 UTC
I followed all of the steps, but it's saying no connection. I was a bit surprised however that it said
`Enter localhost as the Server IP.`
Is this right? I would assume that the server IP would be the server IP...
I also tested changing the IP in the app to the IP of the server, but it still did not connect. What do I do?

**Comment by cpu** [comment] 2017-04-07 22:58
@nakamin What client/platform are you using to connect to the shadowsocks server? Does it output any additional logging or a specific error message? Are you able to ping & ssh to the IP of the server without issue?

**Comment by nakamin** [comment] 2017-04-07 23:01
I'm using Android, there are no logs, and the error it's giving is that it can't connect to google (I assume that's how the app tests the connection). I am able to ping and ssh into the server. Also, I think it might be worth mentioning that I'm using the instructions located [here](https://jerrygamblin.com/2016/07/10/the-vpn-you-should-be-using/), so maybe that's why it won't work.

**Comment by cpu** [comment] 2017-04-08 17:06
Hi @nakamin,

Can you try provisioning your Streisand server from-scratch using the unmodified code from the current master of git? I suspect that your problems may be related to the guide you followed and in order to support you better it would be best if we could rule that out first by following the standard setup procedures with the most recent code.

Thanks!

**Comment by nakamin** [comment] 2017-04-09 13:10
Yeah I'll do that. I'll let you know what happens. Thanks.

**Comment by nakamin** [comment] 2017-04-12 14:53
@cpu so I set up the server following all instructions​. Shadowsocks still doesnt work, even on my home network where there is no blocking. However, Tor and Cisco AnyConnect both work, but only on my home network. On the school network, nothing works. And I can't even pi g my server which leads me to believe that they are blocking it. This is strange, since there is no reason for it to be blocked. I thought that maybe they are blocking any IP that is not a webserver, but I'm not sure how they would be able to verify that (Maybe just send HTTP request to root path and see what comes back?). So is there anything I can do?

**Comment by cpu** [comment] 2017-04-22 16:31
Hi @nakamin - the Shadowsocks server & configuration in Striesand was updated with https://github.com/jlund/streisand/pull/611. Can you try setting up a new Streisand server with the code from master and see if your client is able to connect then? If not we will be in a better position to debug knowing that it affects the up-to-date configuration.

**Comment by tslagle13** [comment] 2017-04-24 02:32
@cpu I have been watching this issue as I have not been able to connect using shadowsocks (my prefered method) either.

I provisioned a new server after pull #611 was merged to master and I still am not able to connect with Shawsocks.

The QR code works fine. The profile imports into Cross but it just sits there saying "starting" indefinitely. 

Anything I can get you from my server to help?

Also, I have tried this on GCE and DO. Both with no success.

**Comment by tiliarou** [comment] 2017-04-27 20:45
I beleive I'm in the same case using shadowsocks 4.0.1 on windows: import works fine, but shadowsocks never manage to connect to the server:
`System.Reflection.TargetInvocationException: Une exception s'est produite lors de l'opération, ce qui rend le résultat non valide. Consultez InnerException pour plus de détails sur l'exception. ---> System.Net.WebException: La connexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de l'envoi. ---> System.IO.IOException: Échec de l'authentification, car le site distant a fermé le flux de transport.
   à System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   à System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   à System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   à System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   à System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- Fin de la trace de la pile d'exception interne ---
   à System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   à Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
`

**Comment by cpu** [comment] 2017-04-27 21:10
@tiliarou @tslagle13 As root on your streisand server can you try adding `-v` to the `DAEMON_ARGS` environment variable in `/etc/default/shadowsocks-libev`, then restart the service with `systemctl restart shadowsocks-libev`.  Once you've done that the server will print more information for connections.

Can you try connecting with the problematic clients & afterwards share the results from `journalctl -u shadowsocks-libev.service --since today --no-pager` in a gist or a pastebin.

Thanks!

**Comment by tiliarou** [comment] 2017-04-27 21:18
[](https://pastebin.com/HWAj0Fw0)
Shadowsock client also shows:
`[2017-04-28 00:14:05] System.Net.Sockets.SocketException (0x80004005): Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée
   à Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   à Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   à Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)`

**Comment by cpu** [comment] 2017-04-29 16:47
@tiliarou to confirm, `37.210.xxx.xxx` in the log is your client IP? I'll have to look into the error messages the server is producing for these attempts, I'm not sure what the problem is at this point. What version of Windows are you running?

**Comment by tiliarou** [comment] 2017-04-29 18:36
Yes, 37.210.xxx.xxx is the client address. Running Shadowsocks client 4.0.1 provided by streisand.
I'm under windows 10, x64, anniversary update 1607, 14393.1066
Do you need more logs ?

**Comment by cpu** [comment] 2017-04-29 19:21
@tiliarou Thanks - I need to spend some time looking at the shadowsocks-libev source to understand what conditions might cause the log statements you observed. In the mean-time, it looks like other people are having trouble with Shadowsocks 4.0.1 on Windows 10: https://github.com/shadowsocks/shadowsocks-windows/issues/1125 Does your experience overlap with theirs at all?

**Comment by tiliarou** [comment] 2017-04-30 05:09
Not sure it's similar, because I didn't upgrade yet to 1703 (creator), I'm still on 1607 (anniversary) windows 10.
They mention also a proxy which I don't have on the client 37.210.xxx.xxx
It says "authentication error" so maybe the password is wrong ? where can I look at manually for the shadowsocks server config file on streisand ? I will also try to manually put credential in shadowsocks client to see if QRcode is good or not.
Else, could it be a firewall configuration error ? Like the firewall is refusing every IP not whitelisted or something similar ?

**Comment by cpu** [comment] 2017-04-30 15:02
> Not sure it's similar, because I didn't upgrade yet to 1703 (creator), I'm still on 1607 (anniversary) windows 10. They mention also a proxy which I don't have on the client 37.210.xxx.xxx

Yeah, seems like a long shot that they'd be related. Thanks for checking.

> It says "authentication error" so maybe the password is wrong ? where can I look at manually for the shadowsocks server config file on streisand ? I will also try to manually put credential in shadowsocks client to see if QRcode is good or not.

Checking the password is a good idea. The config file is `/etc/shadowsocks-libev/config.json` - you will need to be `root` to read it.

> Else, could it be a firewall configuration error ? Like the firewall is refusing every IP not whitelisted or something similar ?

Possible, but seems unlikely, especially since the shadowsocks-libev daemon **is** seeing connections from your client ip. They make it through any firewalls to the daemon and fail with that authentication error.

**Comment by tiliarou** [comment] 2017-04-30 17:07
config.json is good, tried to copy paste password from there, same result.
I digged into shadowsocks server errors: no handshake could means issue between server and client version build. I tried to build shadowsock libev for windows using mingw, but I'm stuck because of select.h not found. Now trying to build with cygwin but I need all dependencies so it's going to take a while... Tried go version go-shadowsocks2n but got `cipher not supported`...

**Comment by tiliarou** [comment] 2017-05-01 08:39
Managed to build ss-local using cygwin64.
But I can't test connection to server now cause my ports are block on my current network, so I can only check tonight.
If anyone wants a windows build of shadowsocks libev : [https://mega.nz/#!F1FF3AjI!LQB4LnSC-elcOK-CG01dLIeNYL7286Q2h1ZpbD95eJ0](https://mega.nz/#!F1FF3AjI!LQB4LnSC-elcOK-CG01dLIeNYL7286Q2h1ZpbD95eJ0)

**Comment by tiliarou** [comment] 2017-05-01 15:46
Getting `getpeername: Transport endpoint is not connected` using my libev build posted above...
So the client cannot see the server ? it's different than a refused connection ?

**Comment by tiliarou** [comment] 2017-05-01 17:19
With Ubuntu shadowsocks 2 client from streisand server, I get ` failed to connect to server 89.40.xxx.xxx:85xx: dial tcp 89.40.xxx.xxx:85xx: getsockopt: connection refused`

**Comment by tiliarou** [comment] 2017-05-20 13:02
any clue on why it's failing to connect to the shadowsock server ?

**Comment by cpu** [comment] 2017-05-20 17:37
@tiliarou I don't have any strong theories at this point. I'd like to set up a Shadowsocks windows client to test with myself but it will take me some time - I don't have a Windows VM with Win10 at hand. I'm afraid I can't promise you a timeline.

Since at this point I don't know that it's necessarily a Streisand specific problem are you willing to try and work through this issue with the Shadowsocks Windows client maintainers? They are likely in a better position to help you troubleshoot. If they believe it's a Streisand issue I can try and find the time to provision a Windows VM to resume troubleshooting from this side.

**Comment by cpu** [comment] 2017-06-16 22:53
I'm going to close this issue since it ran into a dead end in terms of my own ability to support. Thanks for understanding.

**Closed by cpu** 2017-06-16 22:53 UTC
Labels: area/shadowsocks, kind/client, kind/question
