### ISSUE TITLE
Install hangs on 'TASK [l2tp-ipsec : Compile and install Libreswan'

### ISSUE THREAD

**Issue by jamorris** [jlund/streisand#664] opened 2017-05-02 20:34 UTC
Installation to Amazon EC2 hangs at the Libreswan compile and install stage. I've tried installing from a fresh install of Ubuntu 16.04.02 LTS and Fedora 25 (both x64). I can SSH into the EC2 VM. If I disable the l2tp-ipsec roll in streisand.yml then the install hangs at the diffie-hellman-group stage. I did not change the default from 2048-bit in the diffie-hellman-group playbook. I've installed Streisand a few times before and don't believe I'm doing anything differently. Any suggestions on how to see what is hung up on the VM since I can SSH into it?

**Comment by edsai** [comment] 2017-05-03 21:01
The same thing is happening to me as well.

**Comment by jamorris** [comment] 2017-05-09 14:06
I'm using a freshly installed build machine with no alterations other than following the Streisand instructions. It fails as described above on multiple regions. I've made no changes to any files in the ~/streisand folder. Can anyone confirm that they are able to create a new Streaisand server on Amazon EC2 during the past week? If so, what OS and version did you use and did you need to deviate from a generic install in any way?

**Comment by jamorris** [comment] 2017-05-15 17:38
As a workaround I allowed ./streisand to fail then followed the instructions for “Running Streisand on Other Providers”. Running ./streisand does create the virtual machine, key pairs, elastic IP and security groups but fails as described in my initial post. At this point I can successfully run ‘ansible-playbook playbooks/streisand.yml’ after 1st editing ‘inventory’ and ‘ansible.cfg’. The result is a successfully running Streisand server.

**Comment by cpu** [comment] 2017-06-16 23:01
> Can anyone confirm that they are able to create a new Streaisand server on Amazon EC2 during the past week? If so, what OS and version did you use and did you need to deviate from a generic install in any way?

Yes. ArchLinux, Ansible 2.3.1.0, Python 2.7.13. No deviations.

> The result is a successfully running Streisand server.

Since you seem to have resolved the problem by working around it and I can confirm EC2 provisioning appears to be working from my perspective I'm going to close this issue. If you're still encountering the root problem and want to dig further it would be helpful to know your Ansible client versions and to see a full log of the Streisand output. Thanks!

**Closed by cpu** 2017-06-16 23:01 UTC
Labels: area/provisioning, kind/question, provider/amazon, status/help-wanted
