### ISSUE TITLE
Allow configurable local pub key location

### ISSUE THREAD

**Issue by quinncomendant** [jlund/streisand#491] opened 2017-01-27 13:59 UTC
Streisand requires a local public ssh key to be located at `~/.ssh/id_rsa.pub`. If my SSH key is located at `~/.keys/streisand.pub`, Streisand cannot find it. The current workaround is to create a symlink:

    ln -s ~/.keys/streisand.pub ~/.ssh/id_rsa.pub

Would it be reasonable to add a config option to Streisand to specify the location of the SSH key, like this?

    ./streisand --sshkey=~/.keys/streisand.pub

**Comment by Rich700000000000** [comment] 2017-01-28 04:37
Seconded. This could really help out.

**Comment by rosstimson** [comment] 2017-01-30 20:53
Yeah, this would be very handy. I don't necessarily want to use my usual key.  And in fact I've discovered this issue after troubleshooting an issue at `TASK [genesis-amazon : Add the SSH key to Amazon under the name of 'streisand-ssh']`  as my usual key is large which resulted in an error `Length exceeds maximum of 2048`.

**Comment by nickolasclarke** [comment] 2017-01-31 03:48
I also use multiple keys, so prompting for which key I want to use would be great.

**Comment by Rich700000000000** [comment] 2017-01-31 07:20
It should have the ability to make it's own keys, so it's more automated.

**Comment by quinncomendant** [comment] 2017-02-13 12:22
Does the [suggestion](https://github.com/jlund/streisand/issues/300#issuecomment-223844045) offered by @jmusarra in #300 help here?

**Comment by quinncomendant** [comment] 2017-02-13 12:22
Oops, mistakenly click the close button.

**Comment by cpu** [comment] 2017-06-16 22:30
This is a duplicate of https://github.com/jlund/streisand/issues/300 - closing in favour of centralizing discussion there. Thanks!

**Closed by cpu** 2017-06-16 22:30 UTC
Labels: area/ansible, area/provisioning, area/ssh, kind/feature
