### ISSUE TITLE
Automatic IP rotation?

### ISSUE THREAD

**Issue by tedd4u** [jlund/streisand#792] opened 2017-07-08 03:52 UTC
I have to manually rotate IP addresses today which is time consuming and no fun.

### Expected behavior:
Streisand automatically rotates apparent external IP every X minutes.

### Actual Behavior:
No rotation.

**Comment by andreagrax** [comment] 2017-07-08 10:01
Hello Tim,
Could you clarify the behavior you expect?
Do you refer to a specific service or to the whole instance ip?

**Comment by cpu** [comment] 2017-07-08 12:51
Hi @tedd4u, this is a duplicate of https://github.com/jlund/streisand/issues/184 so I'm going to close it.

I recommend you follow #184. This is something the maintainers have talked about and is on our radar but likely won't be supported in the immediate timeframe. 

Thanks!

**Comment by tedd4u** [comment] 2017-07-08 16:19
Yes - I was completely vague. I guess what I want is to have the instance
retain the same IP (call it address A) for OpenVPN access, but to use a
different IP (address B) for outbound / upstream traffic. Further, I'd like
address B to change periodically. Like every 30 minutes or something.
Cycling through new ephemeral IPs.

I guess the argument could be made that I should just use tor, but that's a
big price to pay.

My application is anti-tracking/profiling, not anti-surveillance.

Maybe there are other options?

**Comment by cpu** [comment] 2017-07-08 20:49
Ah, this sounds different than #184. I will reopen.

**Comment by cpu** [comment] 2017-07-23 21:42
Closing in favour of https://github.com/jlund/streisand-discussions/issues/2

**Closed by cpu** 2017-07-23 21:42 UTC
Labels: kind/feature
