### ISSUE TITLE
Fresh server doesn't respond to L2TP

### ISSUE THREAD

**Issue by tcby45** [jlund/streisand#385] opened 2016-08-22 21:48 UTC
Hello! I just tried setting up a Streisand server on DigitalOcean (Singapore, since it's the only country not in the Fourteen Eyes). Getting the SSL certificate and getting into the site works just fine, but no matter what device I try it on (iOS, Windows Phone), I get an error saying that the L2TP server did not respond. I verified that the authentication info was correct, but it still doesn't work. I'm going to try OpenVPN in a little bit and see if that works either.

**Comment by jlund** [comment] 2016-08-24 06:43
I can't reproduce this. L2TP/IPsec is working for me on new DigitalOcean servers in the Singapore region. Have you tried from a different network (WiFi or mobile) by any chance?

**Comment by tcby45** [comment] 2016-08-25 20:51
Finally got the time to. Neither WiFi nor data works. In a bit, I'm going to try destroying the Droplet, `git pull`ing, and recreating it from the new pull.

**Comment by josephlhall** [comment] 2016-08-26 17:12
I know this may be very basic, but have you tried ssh'ing into the droplet and restarting it? That solved a similar problem for me on DO (where neither OpenVPN or L2TP connections were being successfully established).

(To do that, you'd do `ssh root@xxx.xxx.xxx.xxx` and then `sudo shutdown -r now`.)

**Comment by tcby45** [comment] 2016-08-26 18:01
Strangely enough, a fresh server from the latest pull seemed to do the trick. If it stops working, I'll try a reboot and report back.

**Comment by cpu** [comment] 2017-04-08 00:35
It's currently 2017 and there's been no report back of any further problems so I'm going to close this issue. Please feel free to reopen if you are still having trouble with L2TP on a freshly provisioned DigitalOcean machine.

**Closed by cpu** 2017-04-08 00:35 UTC
Labels: area/l2tp, provider/digital-ocean
