### ISSUE TITLE
ami-22de994a in US East not found

### ISSUE THREAD

**Issue by pchaganti** [jlund/streisand#183] opened 2015-07-25 12:09 UTC
Getting this error when running latest version of Streisand using AWS as the cloud provider. That error message from AWS usually indicates that the AMI does not exist any longer or has been restricted in some way and is no longer public. Is there a recommended substitute for this AMI?

thx!

```Shell
TASK: [genesis-amazon | Use the AMI ID for Oregon when the region is us-west-2] ***
skipping: [127.0.0.1]

TASK: [genesis-amazon | Create the EC2 instance] ******************************
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true}
msg: Instance creation failed => AuthFailure: Not authorized for images: [ami-22de994a]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/hades/amazon.retry

127.0.0.1                  : ok=12   changed=4    unreachable=0    failed=1
```

**Comment by pchaganti** [comment] 2015-07-25 12:16
Just found https://github.com/jlund/streisand/issues/174. It sounds like the same issue.

**Comment by df-sh** [comment] 2015-08-07 16:04
use this debian build
https://aws.amazon.com/marketplace/pp/B00AA27RK4

here are the ami from this build:
US East (N. Virginia)	ami-819a63ea
US West (Oregon)	ami-3b56520b	
US West (N. California)	ami-a7d621e3	
EU (Frankfurt)	ami-bc92aaa1
EU (Ireland)	ami-42d89d35
Asia Pacific (Singapore)	ami-6a989c38
Asia Pacific (Sydney)	ami-79e39943
Asia Pacific (Tokyo)	 ami-f454f3f4
South America (Sao Paulo)	ami-a3bd3fbe

**Comment by jlund** [comment] 2015-09-26 02:38
Closing as duplicate of #174.

**Closed by jlund** 2015-09-26 02:38 UTC

**Comment by jlund** [comment] 2015-09-27 00:55
This is fixed.
