### ISSUE TITLE
IPv6 Leaking

### ISSUE THREAD

**Issue by Ev3y** [jlund/streisand#460] opened 2016-12-18 07:27 UTC
Are we going to see IPv6 support anytime soon? Three of the five providers Streisand natively supports (DigitalOcean, Linode, Rackspace) support IPv6, as does Microsoft Azure, native support for which is stated as planned. 
My main concern is not functionality (which will be needed at some point) but privacy. For some devices (e.g. Chromebooks, or at least my Chromebook) there is no easy way to disable IPv6,  and as such my IPv6 leaks. Also, it would protect against leaks for people who use Streisand but fail to properly disable IPv6 on the device they're using.

**Comment by Ev3y** [comment] 2016-12-20 23:54
To be honest, for the time being it doesn't even matter if IPv6 connections are tunneled correctly, just as long as they're tunneled such that IPv6 addresses stop leaking. Maybe while properly configuring IPv6 connections would be difficult, configuring the connection to tunnel IPv6 to nowhere would be relatively easy? Such a solution might even work on providers that don't support IPv6.

**Comment by ev3y2** [comment] 2017-04-02 15:07
So looking into this further, [some VPN providers](https://nordvpn.com/blog/nordvpn-implements-ipv6-leak-protection/) prevent IPv6 leaks by routing IPv6 to nowhere like I mentioned above:

> Technically speaking, when establishing an OpenVPN connection, our clients add additional routes. IPv6 traffic is effectively rerouted to a “black hole” within the device. 

and I came upon [this article](https://nuxx.net/blog/2014/08/05/breaking-ipv6-on-android-openvpn-via-t-mobile/) that details how this can be done - by pushing a broken route from the server.

> By pushing an IPv6 route to the client from OpenVPN I was able to black hole IPv6 on the client and close this leakage. This is done by adding the following to the Advanced configuration section of the OpenVPN server config

`push "route-ipv6 ::/128 ::1"`

Assuming this actually works, this seems like an incredible easy way to prevent IPv6 leaks. If so, I think it should be implemented and kept until proper IPv6 tunneling is introduced.

paging @nickolasclarke because I'm not sure if this issue has gotten lost due to its age, and you seem to be good at testing possible features - would you mind testing the viability of this?

**Comment by cpu** [comment] 2017-04-08 17:00
This looks like a duplicate of https://github.com/jlund/streisand/issues/97. I'm going to close this issue and encourage everyone interested to subscribe to notifications for #97. Thanks!

**Closed by cpu** 2017-04-08 17:00 UTC
Labels: kind/network, kind/privacy, kind/question
