### ISSUE TITLE
Question: UnattendedUpgrades switched on?

### ISSUE THREAD

**Issue by dotben** [jlund/streisand#115] opened 2015-01-19 22:30 UTC
I'm wondering whether Unattended Upgrades (https://wiki.debian.org/UnattendedUpgrades) should be switched on, or at least optionally set at creation, on Streisand instances?

I'm guessing many people will never ssh into their streisand boxes, many may not even keep the private key generated on the server used to run the streisand script.

While it's theoretically possible a backdoor could be loaded into steisand box via this vector, it's highly unlikely, and more likely that an out-of-date service could be pwned using a known issue that was patched in a more recent software update.

**Comment by larryhynes** [comment] 2015-01-27 23:37
I'm also curious about how to maintain and upgrade a Streisand instance once it's set up. I can ssh in as the 'forward' user, but not get very far with that. As far as I knew it would not be possible to ssh in as root, or any other user, or am I wrong on this?

**Comment by jlund** [comment] 2015-02-15 05:29
I think this is a great idea. It's on my list, but I haven't had time to do it yet.

@larryhynes You can SSH in as `root` or `admin`, depending on your provider.

**Comment by brunoqc** [comment] 2015-05-22 15:30
This seems to be a duplicate of #44

**Closed** 2016-01-04 04:11 UTC
