### ISSUE TITLE
Digital Ocean installation fails with `InRelease: Clearsigned file isn't valid, got 'NODATA'`

### ISSUE THREAD

**Issue by derwiki** [jlund/streisand#466] opened 2017-01-02 21:13 UTC
```
Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
:

PLAY [Provision the DigitalOcean Server] ***************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [genesis-digitalocean : Set the DigitalOcean Access Token fact to the value that was entered, or attempt to retrieve it from the environment if the entry is blank] ***
ok: [localhost]

TASK [genesis-digitalocean : Get the default SSH key] **************************
changed: [localhost]

TASK [genesis-digitalocean : Add the SSH key to DigitalOcean if it doesn't already exist] ***
changed: [localhost]

TASK [genesis-digitalocean : Create the new Droplet] ***************************
changed: [localhost]

TASK [genesis-digitalocean : Wait until the server has finished booting and OpenSSH is accepting connections] ***
ok: [localhost]

TASK [genesis-digitalocean : Create the in-memory inventory group] *************
changed: [localhost]

TASK [genesis-digitalocean : Set the streisand_ipv4_address variable] **********
ok: [localhost]

TASK [genesis-digitalocean : Set the streisand_server_name variable] ***********
ok: [localhost]

PLAY [Prepare the new server for Ansible] **************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***
fatal: [138.197.220.218]: FAILED! => {"changed": true, "failed": true, "rc": 100, "stderr": "Warning: Permanently added '138.197.220.218' (RSA) to the list of known hosts.\r\nShared connection to 138.197.220.218 closed.\r\n", "stdout": "\u001b[33m\r0% [Working]\u001b[0m\r            \rGet:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]\r\n\u001b[33m\r0% [Waiting for headers] [1 InRelease 14.2 kB/102 kB 14%]\u001b[0m\r                                                         \rHit:2 http://archive.ubuntu.com/ubuntu xenial InRelease\r\n\u001b[33m\r0% [Waiting for headers] [1 InRelease 14.2 kB/102 kB 14%]\u001b[0m\u001b[33m\r0% [2 InRelease gpgv 0 B] [Waiting for headers] [1 InRelease 14.2 kB/102 kB 14%\u001b[0mSplitting up /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease into data and signature failed\r                                                                               \rErr:2 http://archive.ubuntu.com/ubuntu xenial InRelease\r\n  Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)\r\n\u001b[33m\r                                                                               \r0% [Waiting for headers] [1 InRelease 14.2 kB/102 kB 14%]\u001b[0m\r                                                         \rGet:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]\r\n\u001b[33m\r0% [3 InRelease 14.2 kB/102 kB 14%] [1 InRelease 43.1 kB/102 kB 42%]\u001b[0m\u001b[33m\r                                                                    \r0% [3 InRelease 43.1 kB/102 kB 42%]\u001b[0m\u001b[33m\r0% [1 InRelease gpgv 102 kB] [3 InRelease 43.1 kB/102 kB 42%]\u001b[0m\u001b[33m\r                                                             \r0% [3 InRelease 101 kB/102 kB 99%]\u001b[0m\u001b[33m\r                                  \r0% [Waiting for headers]\u001b[0m\u001b[33m\r0% [3 InRelease gpgv 102 kB] [Waiting for headers]\u001b[0m\u001b[33m\r                                                  \r24% [Waiting for headers]\u001b[0m\r                         \rGet:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [195 kB]\r\n\u001b[33m\r29% [4 Packages 116 kB/195 kB 59%]\u001b[0m\u001b[33m\r                                  \r33% [Waiting for headers]\u001b[0m\u001b[33m\r33% [4 Packages store 0 B] [Waiting for headers] [Waiting for headers]\u001b[0m\r                                                                      \rGet:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [443 kB]\r\n\u001b[33m\r38% [4 Packages store 0 B] [5 Packages 93.7 kB/443 kB 21%] [Waiting for headers\u001b[0m\u001b[33m\r                                                                               \r40% [5 Packages 116 kB/443 kB 26%] [Waiting for headers]\u001b[0m\r                                                        \rGet:6 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [81.0 kB]\r\n\u001b[33m\r                                                        \r44% [5 Packages 116 kB/443 kB 26%]\u001b[0m\u001b[33m\r44% [6 Translation-en store 0 B] [5 Packages 116 kB/443 kB 26%]\u001b[0m\u001b[33m\r                                                               \r52% [5 Packages 268 kB/443 kB 60%]\u001b[0m\u001b[33m\r                                  \r60% [Working]\u001b[0m\u001b[33m\r60% [5 Packages store 0 B]\u001b[0m\u001b[33m\r                          \r61% [Waiting for headers]\u001b[0m\r                         \rGet:7 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [173 kB]\r\n\u001b[33m\r70% [7 Translation-en 173 kB/173 kB 100%]\u001b[0m\u001b[33m\r                                         \r70% [Working]\u001b[0m\u001b[33m\r70% [7 Translation-en store 0 B]\u001b[0m\u001b[33m\r                                \r70% [Waiting for headers]\u001b[0m\r                         \rGet:8 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [6,576 B]\r\n\u001b[33m\r70% [Waiting for headers]\u001b[0m\u001b[33m\r70% [8 Packages store 0 B] [Waiting for headers]\u001b[0m\u001b[33m\r                                                \r71% [Waiting for headers]\u001b[0m\r                         \rGet:9 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Translation-en [2,016 B]\r\n\u001b[33m\r71% [Waiting for headers]\u001b[0m\u001b[33m\r71% [9 Translation-en store 0 B] [Waiting for headers]\u001b[0m\u001b[33m\r                                                      \r72% [Waiting for headers]\u001b[0m\r                         \rGet:10 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [370 kB]\r\n\u001b[33m\r85% [10 Packages 268 kB/370 kB 72%]\u001b[0m\u001b[33m\r                                   \r90% [Working]\u001b[0m\u001b[33m\r90% [10 Packages store 0 B]\u001b[0m\u001b[33m\r                           \r91% [Waiting for headers]\u001b[0m\r                         \rGet:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [136 kB]\r\n\u001b[33m\r97% [Waiting for headers]\u001b[0m\u001b[33m\r97% [11 Translation-en store 0 B] [Waiting for headers]\u001b[0m\u001b[33m\r                                                       \r98% [Waiting for headers]\u001b[0m\r                         \rGet:12 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [7,376 B]\r\n\u001b[33m\r98% [Waiting for headers]\u001b[0m\u001b[33m\r98% [12 Packages store 0 B] [Waiting for headers]\u001b[0m\u001b[33m\r                                                 \r99% [Waiting for headers]\u001b[0m\r                         \rGet:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [3,080 B]\r\n\u001b[33m\r                         \r99% [Working]\u001b[0m\u001b[33m\r99% [13 Translation-en store 0 B]\u001b[0m\u001b[33m\r                                 \r99% [Working]\u001b[0m\r             \r\rReading package lists... 0%\r\rReading package lists... 0%\r\rReading package lists... 1%\r\rReading package lists... 24%\r\rReading package lists... 24%\r\rReading package lists... 38%\r\rReading package lists... 38%\r\rReading package lists... 39%\r\rReading package lists... 39%\r\rReading package lists... 39%\r\rReading package lists... 39%\r\rReading package lists... 61%\r\rReading package lists... 61%\r\rReading package lists... 70%\r\rReading package lists... 70%\r\rReading package lists... 71%\r\rReading package lists... 71%\r\rReading package lists... 71%\r\rReading package lists... 71%\r\rReading package lists... 81%\r\rReading package lists... 81%\r\rReading package lists... 90%\r\rReading package lists... 90%\r\rReading package lists... 90%\r\rReading package lists... 90%\r\rReading package lists... 91%\r\rReading package lists... 91%\r\rReading package lists... 94%\r\rReading package lists... 94%\r\rReading package lists... 95%\r\rReading package lists... 95%\r\rReading package lists... 96%\r\rReading package lists... 96%\r\rReading package lists... 96%\r\rReading package lists... 96%\r\rReading package lists... Done\r\r\nE: GPG error: http://archive.ubuntu.com/ubuntu xenial InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)\r\n", "stdout_lines": ["\u001b[33m", "0% [Working]\u001b[0m", "            ", "Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]", "\u001b[33m", "0% [Waiting for headers] [1 InRelease 14.2 kB/102 kB 14%]\u001b[0m", "                                                         ", "Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease", "\u001b[33m", "0% [Waiting for headers] [1 InRelease 14.2 kB/102 kB 14%]\u001b[0m\u001b[33m", "0% [2 InRelease gpgv 0 B] [Waiting for headers] [1 InRelease 14.2 kB/102 kB 14%\u001b[0mSplitting up /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease into data and signature failed", "                                                                               ", "Err:2 http://archive.ubuntu.com/ubuntu xenial InRelease", "  Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)", "\u001b[33m", "                                                                               ", "0% [Waiting for headers] [1 InRelease 14.2 kB/102 kB 14%]\u001b[0m", "                                                         ", "Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]", "\u001b[33m", "0% [3 InRelease 14.2 kB/102 kB 14%] [1 InRelease 43.1 kB/102 kB 42%]\u001b[0m\u001b[33m", "                                                                    ", "0% [3 InRelease 43.1 kB/102 kB 42%]\u001b[0m\u001b[33m", "0% [1 InRelease gpgv 102 kB] [3 InRelease 43.1 kB/102 kB 42%]\u001b[0m\u001b[33m", "                                                             ", "0% [3 InRelease 101 kB/102 kB 99%]\u001b[0m\u001b[33m", "                                  ", "0% [Waiting for headers]\u001b[0m\u001b[33m", "0% [3 InRelease gpgv 102 kB] [Waiting for headers]\u001b[0m\u001b[33m", "                                                  ", "24% [Waiting for headers]\u001b[0m", "                         ", "Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [195 kB]", "\u001b[33m", "29% [4 Packages 116 kB/195 kB 59%]\u001b[0m\u001b[33m", "                                  ", "33% [Waiting for headers]\u001b[0m\u001b[33m", "33% [4 Packages store 0 B] [Waiting for headers] [Waiting for headers]\u001b[0m", "                                                                      ", "Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [443 kB]", "\u001b[33m", "38% [4 Packages store 0 B] [5 Packages 93.7 kB/443 kB 21%] [Waiting for headers\u001b[0m\u001b[33m", "                                                                               ", "40% [5 Packages 116 kB/443 kB 26%] [Waiting for headers]\u001b[0m", "                                                        ", "Get:6 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [81.0 kB]", "\u001b[33m", "                                                        ", "44% [5 Packages 116 kB/443 kB 26%]\u001b[0m\u001b[33m", "44% [6 Translation-en store 0 B] [5 Packages 116 kB/443 kB 26%]\u001b[0m\u001b[33m", "                                                               ", "52% [5 Packages 268 kB/443 kB 60%]\u001b[0m\u001b[33m", "                                  ", "60% [Working]\u001b[0m\u001b[33m", "60% [5 Packages store 0 B]\u001b[0m\u001b[33m", "                          ", "61% [Waiting for headers]\u001b[0m", "                         ", "Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [173 kB]", "\u001b[33m", "70% [7 Translation-en 173 kB/173 kB 100%]\u001b[0m\u001b[33m", "                                         ", "70% [Working]\u001b[0m\u001b[33m", "70% [7 Translation-en store 0 B]\u001b[0m\u001b[33m", "                                ", "70% [Waiting for headers]\u001b[0m", "                         ", "Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [6,576 B]", "\u001b[33m", "70% [Waiting for headers]\u001b[0m\u001b[33m", "70% [8 Packages store 0 B] [Waiting for headers]\u001b[0m\u001b[33m", "                                                ", "71% [Waiting for headers]\u001b[0m", "                         ", "Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Translation-en [2,016 B]", "\u001b[33m", "71% [Waiting for headers]\u001b[0m\u001b[33m", "71% [9 Translation-en store 0 B] [Waiting for headers]\u001b[0m\u001b[33m", "                                                      ", "72% [Waiting for headers]\u001b[0m", "                         ", "Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [370 kB]", "\u001b[33m", "85% [10 Packages 268 kB/370 kB 72%]\u001b[0m\u001b[33m", "                                   ", "90% [Working]\u001b[0m\u001b[33m", "90% [10 Packages store 0 B]\u001b[0m\u001b[33m", "                           ", "91% [Waiting for headers]\u001b[0m", "                         ", "Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [136 kB]", "\u001b[33m", "97% [Waiting for headers]\u001b[0m\u001b[33m", "97% [11 Translation-en store 0 B] [Waiting for headers]\u001b[0m\u001b[33m", "                                                       ", "98% [Waiting for headers]\u001b[0m", "                         ", "Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [7,376 B]", "\u001b[33m", "98% [Waiting for headers]\u001b[0m\u001b[33m", "98% [12 Packages store 0 B] [Waiting for headers]\u001b[0m\u001b[33m", "                                                 ", "99% [Waiting for headers]\u001b[0m", "                         ", "Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [3,080 B]", "\u001b[33m", "                         ", "99% [Working]\u001b[0m\u001b[33m", "99% [13 Translation-en store 0 B]\u001b[0m\u001b[33m", "                                 ", "99% [Working]\u001b[0m", "             ", "", "Reading package lists... 0%", "", "Reading package lists... 0%", "", "Reading package lists... 1%", "", "Reading package lists... 24%", "", "Reading package lists... 24%", "", "Reading package lists... 38%", "", "Reading package lists... 38%", "", "Reading package lists... 39%", "", "Reading package lists... 39%", "", "Reading package lists... 39%", "", "Reading package lists... 39%", "", "Reading package lists... 61%", "", "Reading package lists... 61%", "", "Reading package lists... 70%", "", "Reading package lists... 70%", "", "Reading package lists... 71%", "", "Reading package lists... 71%", "", "Reading package lists... 71%", "", "Reading package lists... 71%", "", "Reading package lists... 81%", "", "Reading package lists... 81%", "", "Reading package lists... 90%", "", "Reading package lists... 90%", "", "Reading package lists... 90%", "", "Reading package lists... 90%", "", "Reading package lists... 91%", "", "Reading package lists... 91%", "", "Reading package lists... 94%", "", "Reading package lists... 94%", "", "Reading package lists... 95%", "", "Reading package lists... 95%", "", "Reading package lists... 96%", "", "Reading package lists... 96%", "", "Reading package lists... 96%", "", "Reading package lists... 96%", "", "Reading package lists... Done", "", "E: GPG error: http://archive.ubuntu.com/ubuntu xenial InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)"]}
       	to retry, use: --limit @/Users/adam/src/streisand/playbooks/digitalocean.retry

PLAY RECAP *********************************************************************
138.197.220.218            : ok=0    changed=0    unreachable=0    failed=1
localhost                  : ok=9    changed=4    unreachable=0    failed=0
```

**Comment by ryanohoro** [comment] 2017-01-03 19:35
I wasn't able to reproduced the problem, however Streisand is using the wrong repositories to install Python. Try the patch associated with Issue #457

**Comment by jlund** [comment] 2017-01-12 03:51
I cannot reproduce this issue anymore now that the `cloud-status.yml` check has been merged \o/

**Closed by jlund** 2017-01-12 03:51 UTC
