### ISSUE TITLE
USE WINDOWS with STREISAND

### ISSUE THREAD

**Issue by kar2013** [jlund/streisand#719] opened 2017-06-01 10:00 UTC
Hi,

Someone can say me if it's possible to use STREISAND with windows ISO ?

Thanks for help.

**Comment by alimakki** [comment] 2017-06-01 14:26
Do you mean running the Streisand script from a Windows machine?

**Comment by kar2013** [comment] 2017-06-01 17:26
Not necessarily, if there is another way I am taker.

The goal is to benefit from the streisand service in a Windows environment

I use the cloud digitalocean and debian 0S

Thanks

**Comment by alimakki** [comment] 2017-06-02 01:12
@kar2013 From what I understand, It is not currently possible to install Streisand on a Windows server. 
It is possible for Windows clients, such as your PC, to utilize the various VPNs Streisand offers (with the exception of WireGuard), as such all customized instructions are generated for you as part of the process.

If on the other hand, you have a Windows PC and you wish to use that to create a new Streisand server, it is possible by using the Windows Subsystem for Linux, see this separate [issue](https://github.com/jlund/streisand/issues/710).

I hope that answers your question!

**Comment by kar2013** [comment] 2017-06-02 06:16
alimakki thaks a lot for your answer,

It's a little bit diffuclt for me but i try to undersand .

Someone know where i can find a documentation or tuto on this ?

Thanks all

**Comment by alimakki** [comment] 2017-06-02 11:04
@kar2013 This is the documentation for install [https://msdn.microsoft.com/en-us/commandline/wsl/install_guide](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).

Once you have it up and running, you simply follow the same instructions as you would if you were using Ubuntu.

**Comment by cpu** [comment] 2017-06-02 14:07
Since it sounds like this is a duplicate of #710 and you have a link to the documentation from Ali I'm going to close this issue. Thanks!

**Closed by cpu** 2017-06-02 14:07 UTC
Labels: kind/question
