### ISSUE TITLE
How can I custom choose which service that I want to install

### ISSUE THREAD

**Issue by ookangzheng** [jlund/streisand#510] opened 2017-02-11 12:42 UTC
I using budgetvm ,openvz, ubuntu16.04
I get the error during shadowsocks part
<img width="1172" alt="screenshot 2017-02-11 13 35 59" src="https://cloud.githubusercontent.com/assets/6301735/22853807/bc5cfbd0-f05f-11e6-9e52-043ac1a670a7.png">

I also wanna do a custom Install, for example: I dont need shadowsocks and wireguard how can I uncheck them ?

Thanks

**Comment by sjug** [comment] 2017-02-12 00:33
Oh you need Wireguard as it's the future.

However I have the same general question. Would it be possible to put toggles in to not install _everything_?

**Comment by sjug** [comment] 2017-02-12 12:35
Shadowsocks is no longer compatible with ubuntu 16.04. I tried compiling as they suggest as well, but libsodium in 16.04 is not new enough. 
`Need to be ubuntu 16.10 with libsodium 1.0.10 at least`

**Comment by ookangzheng** [comment] 2017-02-12 14:04
Yesterday I tried successful, for exp
I delete the 
1. streisand.yml -> roles: -> delete shadowsocks options
2. ufw -> tasks -> main.yml -> delete shadowsocks part
3. streisand-mirror -> tasks folder-> delete shadowsocks.yml file && vars folder -> delete shadowsocks.yml files too
4. In streisand-mirror -> main.yml (download and verify ) delete the shadowsocks option
5. then in current dir/template -> mirror-index.md.j2 file -> delete shadowsocks part
Done~

**Comment by ookangzheng** [comment] 2017-02-12 14:07
@sjug  b4 i use streisand, I use openvpn and shadowsocks as usual. I use this script ( author from china)
https://teddysun.com/486.html

just paste the code and install it (remember open the firewall port)

`wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-all.sh
chmod +x shadowsocks-all.sh
./shadowsocks-all.sh 2>&1 | tee shadowsocks-all.log`

**Comment by alimakki** [comment] 2017-02-12 15:10
you can work around the shadowsocks portion by editing the shadowsocks playbooks/shadowsocks/tasks/main.yml file manually and harcoding `trusty` as such:

name: Add the Shadowsocks-libev repository
  apt_repository:
    repo: 'deb https://shadowsocks.org/{{ ansible_distribution|lower }} trusty main'
    state: present

**Comment by quinncomendant** [comment] 2017-02-13 12:19
Yes, it would be great to be able to exclude services that won't be used. This can be during the interactive setup session, or via command line args, `--disable-shadowsocks`, `--disable-tor`, etc.

**Comment by andreagrax** [comment] 2017-02-13 12:25
I agree .
I tried to fiddle about this , but is seems that there are many cross references between the various roles .
It's also mentioned in another issue but I can't find it just now...

**Comment by quinncomendant** [comment] 2017-02-13 13:38
BTW, I don't mean to say adding a feature to exclude services is an acceptable solution to the errors people are getting here. That also needs to get fixed. I noticed this is happening to me now too (`The repository 'http://shadowsocks.org/ubuntu trusty Release' does not have a Release file`).

**Comment by sjug** [comment] 2017-02-13 13:40
@quinncomendant I've been working on a PR to fix the issue but it's definitely unraveled the whole nest. Shadowsocks no longer supports Ubuntu 16.04, even building from source. Like I said yesterday above.

**Comment by macuser666** [comment] 2017-02-13 21:03
I get the same error
Streisand server deployment fails whilst trying to install Shadowsocks

**Comment by dlin303** [comment] 2017-02-14 22:10
@sjug Can you elaborate a little more about how to do option 2?

**Comment by sjug** [comment] 2017-02-14 22:33
@dlin303 For option 2, we would need to find out what the last version of shadowsocks was which supports the 16.04 version of [libsodium](https://launchpad.net/ubuntu/+source/libsodium/1.0.8-5) (1.0.8) then use the [binaries](https://github.com/shadowsocks/shadowsocks-libev/releases).

Hopefully @jlund returns soon so he can merge in the PRs to fix this blocker.

**Comment by jlund** [comment] 2017-02-15 05:46
A fix for the Shadowsocks repository issue has been merged, and work on role selection (e.g. being able to reliably comment out services that you do not want or need) is already in progress. I hope to have it finished this weekend.

**Comment by jlund** [comment] 2017-02-15 06:35
BTW there won't be any need to move to a non-LTS release of Ubuntu for the sake of Shadowsocks.

**Comment by hosaka** [comment] 2017-02-16 21:45
I wish I found this thread before deploying all the defaults! Looking forward to selective install. All I would like to try using is wireguard, so commenting out the majority of the roles shouldn't be a problem in streisand.yml?

**Comment by TauZero** [comment] 2017-03-17 15:54
Any word on how the role selection is going? Trying to do some planning and an updated time estimate would be helpful. Thanks!

**Comment by tiliarou** [comment] 2017-04-19 20:13
so in the end, if we are on 16.10, will openvpn and shadowsock work as of today streisand git master ?

**Comment by cpu** [comment] 2017-06-20 00:38
There are several open issues of varying age/concentration on modularization to date. I've started on a concerted effort to implement first-party support and recommend interested parties follow https://github.com/jlund/streisand/issues/746. I'm going to close this issue as a duplicate of 746 in the short term. Thanks!

**Closed by cpu** 2017-06-20 00:38 UTC
Labels: area/ansible, area/provisioning, kind/feature
