### ISSUE TITLE
Openvpn Not Installed on Digital Ocean Droplet.

### ISSUE THREAD

**Issue by ianbarton** [jlund/streisand#920] opened 2017-09-04 12:56 UTC
I have just setup a Digital Ocean droplet using the Ubuntu ansible script. The installation seems to have completed without any errors. I was intending to use the server as an openvpn server. All the certificates have been generated, but openvpn doesn't appear to have been installed.

  sudo dpkg -l openvpn    
  sudo: unable to resolve host streisand
  dpkg-query: no packages found matching openvpn

I am installing from Arch Linux.

ansible --version

  dell src/streisand ‹master*› » ansible --version                                                                                                         

  ansible 2.3.2.0
  config file = /home/ian/src/streisand/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]

**Comment by nopdotcom** [comment] 2017-09-04 16:07
If you want to just get a server up and running while we debug this, deploy from yet another a droplet running Ubuntu 16.04 LTS. I wrote a [`cloud-init` script to configure necessary packages](https://gist.github.com/nopdotcom/f7f148ce57f2728b9747e8b5ad9066c5). Here’s where to paste it:

![capto_capture 2017-09-04_11-09-03_am](https://user-images.githubusercontent.com/1357866/30032411-c9e47e36-9163-11e7-88ba-c13e60b546fa.png)

**Comment by ianbarton** [comment] 2017-09-06 07:48
Thanks. I did try your solution, but same result, OpenVPN not installed. However, when I installed on the droplet running 16.04 using the Localhost option, OpenVPN was successfully installed.

**Comment by alimakki** [comment] 2017-09-06 12:32
Hi @ianbarton, 

Can you let me know the output from `git rev-parse HEAD` from the initial attempt?

I haven't been able to reproduce your issue on my end.

**Comment by alimakki** [comment] 2017-09-06 14:06
@ianbarton,

I tried spinning up a new Streisand server off of master on a DO droplet; I can see OpenVPN and confirmed that I am able to connect.

![screen shot 2017-09-06 at 10 05 07 am](https://user-images.githubusercontent.com/920624/30116206-f4124dc2-92ea-11e7-92d8-61a474fb106d.png)
![screen shot 2017-09-06 at 10 06 33 am](https://user-images.githubusercontent.com/920624/30116235-00c42018-92eb-11e7-9e8d-080159a63de6.png)

**Comment by cpu** [comment] 2017-09-11 17:23
Closing this issue since it's gone 5 days without a reply providing the required information. Please re-open if you are able to provide more information. Thanks!

**Closed by cpu** 2017-09-11 17:23 UTC
Labels: area/openvpn, kind/bug, provider/digital-ocean, status/information-needed
