### ISSUE TITLE
IPsec/L2TP on AWS

### ISSUE THREAD

**Issue by trexx** [jlund/streisand#311] opened 2016-06-02 13:50 UTC
"Streisand does not install L2TP/IPsec on Amazon EC2 or Google GCE servers by default because the instances cannot bind directly to their public IP addresses which makes IPsec routing nearly impossible."

IPsec does not need to bind directly to the public IP.
For Amazon anyway, left should be the private IP of the instance, leftid should be the Elastic IP associated with said instance. Use the Elastic IP in secrets for matching PSK and tunnels will establish. L2TP should also naturally work once the tunnel is established. Obviously ensure ports 500, 4500 and IP Protocol 50 (ESP) are open in security groups.
I managed a similar setup and it worked (until we replaced it with OpenVPN)

left={{ ansible_default_ipv4.address }}
leftid={{ ansible_default_ipv4.address }}

**Comment by DavidWittman** [comment] 2016-08-02 16:15
:+1: I can confirm this configuration works just fine on AWS.

**Comment by jlund** [comment] 2016-08-05 05:17
Merged! Thanks, @DavidWittman.

**Closed by jlund** 2016-08-05 05:17 UTC

**Comment by joopdorresteijn** [comment] 2017-01-15 01:57
Not sure if solved.

```
Jan 15 01:10:57 almond pluto[14007]: added connection description "nm-ipsec-l2tp-13411"
Jan 15 01:10:57 almond pluto[14007]: "nm-ipsec-l2tp-13411" #1: initiating Main Mode
Jan 15 01:10:57 almond NetworkManager[410]: 002 "nm-ipsec-l2tp-13411" #1: initiating Main Mode
Jan 15 01:10:57 almond NetworkManager[410]: 104 "nm-ipsec-l2tp-13411" #1: STATE_MAIN_I1: initiate
Jan 15 01:10:57 almond pluto[14007]: "nm-ipsec-l2tp-13411" #1: transition from state STATE_MAIN_I1 to state STATE_MAIN_I2
Jan 15 01:10:57 almond NetworkManager[410]: 002 "nm-ipsec-l2tp-13411" #1: transition from state STATE_MAIN_I1 to state STATE_MAIN_I2
Jan 15 01:10:57 almond NetworkManager[410]: 106 "nm-ipsec-l2tp-13411" #1: STATE_MAIN_I2: sent MI2, expecting MR2
Jan 15 01:10:57 almond pluto[14007]: "nm-ipsec-l2tp-13411" #1: STATE_MAIN_I2: sent MI2, expecting MR2
Jan 15 01:10:58 almond pluto[14007]: "nm-ipsec-l2tp-13411" #1: transition from state STATE_MAIN_I2 to state STATE_MAIN_I3
Jan 15 01:10:58 almond pluto[14007]: "nm-ipsec-l2tp-13411" #1: STATE_MAIN_I3: sent MI3, expecting MR3
Jan 15 01:10:58 almond NetworkManager[410]: 002 "nm-ipsec-l2tp-13411" #1: transition from state STATE_MAIN_I2 to state STATE_MAIN_I3
Jan 15 01:10:58 almond NetworkManager[410]: 108 "nm-ipsec-l2tp-13411" #1: STATE_MAIN_I3: sent MI3, expecting MR3
**Jan 15 01:10:58 almond pluto[14007]: "nm-ipsec-l2tp-13411" #1: Main mode peer ID is ID_IPV4_ADDR: 'b.b.b.b'
Jan 15 01:10:58 almond pluto[14007]: "nm-ipsec-l2tp-13411" #1: we require IKEv1 peer to have ID 'a.a.a.a', but peer declares 'b.b.b.b'**
```

**Comment by joopdorresteijn** [comment] 2017-01-15 03:10
It was solved. My bad. I tested on mobile phone and it connected instantly. Turns out for AWS I need to define both. (Local machine runs libreswan):

     right=IPOFSERVER
     rightsubnet=172.31.12.0/24
     rightid=172.31.12.172
     rightprotoport=17/1701

The rightID was essential to get past IKE
