### ISSUE TITLE
Stuck at TASK [genesis-amazon : Determine which AMI to use] step

### ISSUE THREAD

**Issue by Xentrk** [jlund/streisand#668] opened 2017-05-06 08:32 UTC
I have gotten around several errors in my attempt to get this service tested.  I am using a raspberry pi3 as my local machine and Amazon AWS as my Ubuntu server in the cloud.

I am stuck at this step of the process when running ./streisand:
 
`TASK [genesis-amazon : Determine which AMI to use] *********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Image' object has no attribute 'creationDate'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_tQBkcT/ansible_module_ec2_ami_find.py\", line 439, in <module>\n    main()\n  File \"/tmp/ansible_tQBkcT/ansible_module_ec2_ami_find.py\", line 393, in main\n    'creationDate': image.creationDate,\nAttributeError: 'Image' object has no attribute 'creationDate'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}`

Any help is greatly appreciated!

**Comment by Xentrk** [comment] 2017-05-06 14:05
I did more searching on the web and see others reporting this issue. Here is one example
https://github.com/ansible/ansible-modules-core/issues/4522
Tried updating boto and commenting out line 393 as posted on some threads as workaround solutions.  Unfortunately, this did not work for me.

**Comment by cpu** [comment] 2017-05-07 12:58
@Xentrk How did you install Ansible and its dependencies? Reading the linked Ansible issue it sounds like this is caused by an outdated `boto` library and I'm not sure how Streisand can address that problem on a provisioning machine.

**Comment by Xentrk** [comment] 2017-05-08 04:14
Hi Daniel,
Thanks for the reply.  Unfortunately, I don't have the logs from my ssh session to validate. I followed the instructions on the website. There were some errors along the way and did some updates on the packages in an attempt to get past them.  I have a raspberry pi3 with Ubuntu jessie as the provisioning machine.  I installed using the sudo pip install ansible markupsafe. It will be difficult for me to try and reproduce.  Since I was able to complete the server setup, I don't want to try and mess things up by trying to run the program again.   

Regards, Doug Wood

**Comment by cpu** [comment] 2017-05-20 02:04
Hi @Xentrk, since it sounds like you took a number of non-standard steps to work around errors & aren't able to reproduce I'm going to close this issue. Thanks, please open a new issue if you run into any trouble with the Streisand instance you have now.

**Closed by cpu** 2017-05-20 02:04 UTC
Labels: area/provisioning, provider/amazon, status/information-needed
