### ISSUE TITLE
Amazon Web Services NOT US East cannot resolve Ubuntu

### ISSUE THREAD

**Issue by df-sh** [jlund/streisand#219] opened 2015-12-27 03:17 UTC
Servers that arent US East have trouble connecting to Ubuntu archives for apt.  The issue is described at this link

https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/615545

**Comment by genewitch** [comment] 2015-12-27 04:04
Is this a bug with streisand, or the ubuntu maintained AMIs?

**Comment by df-sh** [comment] 2015-12-31 15:07
Its a bug with how the maintained ami's dns resolvers.  can be fixed by adding a non region specific ubuntu source to apt.

**Comment by jlund** [comment] 2016-01-04 03:43
I updated the Ubuntu AMI IDs to use the latest official Trusty release (20151218) and I can no longer replicate this issue.

@df-sh Can you confirm that this is working for you now as well?

**Comment by df-sh** [comment] 2016-01-04 08:19
using latest commit and deploying an amazon server in us west 1 (option 8) leads to this error:

TASK: [common | Install Streisand common packages] **************************** 
failed: [ip removed] => (item=curl,gnupg,markdown,openntpd,python-software-properties,qrencode,unattended-upgrades,wamerican-huge) => {"failed": true, "item": "curl,gnupg,markdown,openntpd,python-software-properties,qrencode,unattended-upgrades,wamerican-huge"}
stderr: E: There are problems and -y was used without --force-yes

stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  dictionaries-common libqrencode3
Suggested packages:
  ispell aspell hunspell wordlist emacsen-common jed-extra
The following NEW packages will be installed:
  dictionaries-common libqrencode3 markdown openntpd
  python-software-properties qrencode wamerican-huge
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 1265 kB of archives.
After this operation, 5097 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  python-software-properties

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'markdown' 'openntpd' 'python-software-properties' 'qrencode' 'wamerican-huge'' failed: E: There are problems and -y was used without --force-yes


FATAL: all hosts have already failed -- aborting

**Comment by jlund** [comment] 2016-01-17 22:04
I cannot replicate this in us-west-2 or any other region. I just updated the AMI list again today if you want to try again.

Is it possible that any changes have been made to the default VPC in us-west-2 in your account? You can disable DNS resolution for a VPC, for example.

**Comment by df-sh** [comment] 2016-02-01 00:07
I cannot replicate this issue anymore, so it looks like latest AMI list resolves the issues.

I was getting this error on multiple amazon accounts prior to this working... so not what the exact issue was... but its gone for now!

**Comment by rennaisance-dangelo** [comment] 2016-02-21 06:50
I seem to have the same issue with a Ubuntu 14.04 vps located in Tokyo. However, I am on Vultr. Any idea how to resolve this?
Thanks!

**Comment by cpu** [comment] 2017-04-08 02:48
@dl-sh confirmed they can't replicate this issue anymore and it looks like @denoza split their Vultr issue into #258 which has since been closed. I'm going to close this issue as well since it doesn't seem actionable anymore. Thanks!

**Closed by cpu** 2017-04-08 02:48 UTC
Labels: area/dns, area/host, kind/network, provider/amazon
