### ISSUE TITLE
Wireguard parse error

### ISSUE THREAD

**Issue by tobiasboyd** [jlund/streisand#691] opened 2017-05-19 21:52 UTC
I can't seem to connect to my DO Streisand instance via Wireguard as of around 5/18:

```
$ wg-quick up wg0-client
[#] ip link add wg0-client type wireguard
[#] wg setconf wg0-client /dev/fd/63
Line unrecognized: `PresharedKey=XXXXX'
Configuration parsing error
[#] ip link delete dev wg0-client
```

Have there been breaking changes to wg conf files recently? I re-downloaded the `wg0-client` that was generated by ansible from my droplet, it's identical, and throws the same error. I can connect via OpenVPN without any problems.

**Comment by cpu** [comment] 2017-05-20 01:57
@tobiasboyd What is your client's operating system? Can you share the versions of both the `wireguard-dkms` and  `wireguard-tools` packages you installed on the client?

**Comment by zx2c4** [comment] 2017-05-20 13:16
Hi @tobiasboyd -- After you `apt update && apt upgrade`, remember to unload the old module and then reload the new one: `rmmod wireguard; modprobe module`. After you should see `0.0.20170517` when doing `cat /sys/module/wireguard/version`. Alternatively, you can just restart.

**Comment by tobiasboyd** [comment] 2017-05-22 16:44
@cpu - client is Ubuntu 16.10. 
```
$ cat /sys/module/wireguard/version
0.0.20170517
```
@zx2c4 thanks for those suggestions, I commented out the preshared key in both server and client conf files, and also renamed the preshared key file on the server. Connecting works fine now.

**Comment by cpu** [comment] 2017-05-22 16:48
@tobiasboyd Thanks. We've merged https://github.com/jlund/streisand/pull/692 which removes the `PresharedKey` directives in the server/client configs that Streisand generates. I'm going to close this issue since the root cause should now be resolved.

**Closed by cpu** 2017-05-22 16:48 UTC
Labels: area/wireguard, kind/client, kind/question
