### ISSUE TITLE
shadowsocks simple-obfs git clone breaks with local modifications error

### ISSUE THREAD

**Issue by bino7** [jlund/streisand#788] opened 2017-07-06 17:29 UTC
### Steps to Reproduce:
1. 
TASK [shadowsocks : Clone the simple-obfs source code at tag 0.0.3] ************
fatal: [localhost]: FAILED! => {"before": "1f5dcace9ee50da6144824b9db9e89be889a9033", "changed": false, "failed": true, "msg": "Local modifications exist in repository (force=no)."}
        to retry, use: --limit @/root/streisand/playbooks/localhost.retry

PLAY RECAP *********************************************************************
localhost                  : ok=147  changed=29   unreachable=0    failed=1

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
TASK [shadowsocks : Clone the simple-obfs source code at tag 0.0.3] ************
fatal: [localhost]: FAILED! => {"before": "1f5dcace9ee50da6144824b9db9e89be889a9033", "changed": false, "failed": true, "msg": "Local modifications exist in repository (force=no)."}
##### *Target Cloud Provider:*
digitalocean
##### *Operating System of target host:*
Ubuntu 16.04.2 x64
##### *Operating System of client:*
Ubuntu 16.04.2 x64
##### *Version of Ansible, using `ansible --version` :*
ansible 2.3.1.0

**Comment by cpu** [comment] 2017-07-06 17:44
Hi @bino7 - I have a fix for this locally that I will publish after I finish work.

In the meantime it should be sufficient to add "force: yes" after [this line](https://github.com/jlund/streisand/blob/master/playbooks/roles/shadowsocks/tasks/simple-obfs.yml#L6) in `playbooks/roles/shadowsocks/tasks/simple-obfs.yml`

**Comment by bino7** [comment] 2017-07-06 18:05
thanks, install finished.

**Comment by cpu** [comment] 2017-07-07 00:26
@bino7 Glad to hear you were unblocked.

I updated the title of this issue to reflect the root cause and opened a PR with the fix: https://github.com/jlund/streisand/pull/789

**Closed** 2017-07-07 00:31 UTC
Labels: area/shadowsocks, kind/bug

**Comment by cpu** [comment] 2017-07-07 00:34
And fixed in master! Thanks for reporting.
