### ISSUE TITLE
wireguard network interface set up ok, but can't connect to internet after wireguard interface is up

### ISSUE THREAD

**Issue by jenenliu** [jlund/streisand#606] opened 2017-04-15 13:08 UTC
Hi, thanks for your awesome project.
I have set streisand successfully with Linode, and want to run a wireguard vpn.
I follow the instruction, and the interface is up ok, but after it is up, there are two kinds of result.
1. Can't connect to the internet.
`jenenliu@think-gentoo ~ $ ping www.bing.com`
     ping: unknown host www.bing.com

2. I can open some websites, but still can't open block website like google (I am in China), and I open bing.com and search 'ip', the result is the ip of Linode.

Below is some of my information:
1.  wg0-client.conf
`think-gentoo jenenliu # cat /etc/wireguard/wg0-client.conf `
[Interface]
Address = 10.192.122.2/32
PostUp = echo nameserver 10.192.122.1 | resolvconf -a %i -m 0 -x
PostDown = resolvconf -d %i
PrivateKey = privatekey
PresharedKey = presharedkey
[Peer]
PublicKey = pubKey
AllowedIPs = 0.0.0.0/0
Endpoint = LinodeIp:51820

2. output of 'wg-quick up' and 'wg show'
`jenenliu@think-gentoo ~ $ sudo wg-quick up wg0-client`
[#] ip link add wg0-client type wireguard
[#] wg setconf wg0-client /dev/fd/63
[#] ip address add 10.192.122.2/32 dev wg0-client
[#] ip link set wg0-client up
[#] wg set wg0-client fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0-client table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] echo nameserver 10.192.122.1 | resolvconf -a wg0-client -m 0 -x
`jenenliu@think-gentoo ~ $ sudo wg show`
  interface: wg0-client
  public key: pubkey
  private key: (hidden)
  pre-shared key: (hidden)
  listening port: 51790
  fwmark: 0xca6c

peer: peerkey
  endpoint: LinodeIp:51820
  allowed ips: 0.0.0.0/0
  transfer: 0 B received, 1.59 KiB sent

3. ifconfig output of wg interface
wg0-client: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.192.122.2  netmask 255.255.255.255  destination 10.192.122.2
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10  bytes 2600 (2.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

I try some search and read the doc of wireguard, but still can't make it, is it because the wrong 
configuration or some other issue, any hint or advice is appreciate, and again, thanks a lot.

**Comment by cpu** [comment] 2017-04-15 15:56
Hi @jenenliu, thanks for all of the detailed information!

> jenenliu@think-gentoo ~ $ ping www.bing.com
> ping: unknown host www.bing.com

Can you share the contents of `/etc/resolv.conf` after you've brought the wg0-client interface up? I'm wondering if resolvconf is dropping the ball and not adding the wireguard nameserver. If that's not the case I'm out of immediate theories :-X

**Comment by jenenliu** [comment] 2017-04-15 16:00
Hi @cpu , thanks for reply.
This is the `/etc/resolv.conf` file, the first line is comment.

> Generated by resolvconf
> nameserver 10.192.122.1

**Comment by cpu** [comment] 2017-04-15 16:05
@jenenliu - Thanks for the quick follow-up. So that does seem correct :-/ 

When you describe the two kinds of results: 1) - no internet at all 2) - no access to blocked sites, can you describe the frequency each happens? Can you try using Shadowsocks or an alternative service to wireguard during these periods to see if they are also producing result 1 or 2?

Out of curiosity, how long have you been using this Linode Streisand server?

**Comment by jenenliu** [comment] 2017-04-15 16:11
@cpu , I use Linode Streisand server for about a week, and I use l2tp/sec for my Android, it is working fine. I try to run a openvpn or openconnect vpn, but I am failed.

> Can you try using Shadowsocks or an alternative service to wireguard during these periods to see if they are also producing result 1 or 2?

Do you mean, that I can try set a Shadowsocks vpn to see if they producing result 1 or 2 ?
Btw, I can't receive packages but can send using Shadowsocks on my Android phone.

**Comment by jenenliu** [comment] 2017-04-15 16:19
@cpu , and this is another information
> PING 10.192.122.1 (10.192.122.1) 56(84) bytes of data.
ping: sendmsg: No buffer space available
ping: sendmsg: No buffer space available
ping: sendmsg: No buffer space available
^C
--- 10.192.122.1 ping statistics ---
11 packets transmitted, 0 received, 100% packet loss, time 29254ms

**Comment by zx2c4** [comment] 2017-04-15 17:06
> I have set streisand successfully with Linode, and want to run a wireguard vpn.

As discussed elsewhere, no, you did not. This is a duplicate of #500. Please close.

**Closed** 2017-04-15 17:08 UTC
Labels: area/wireguard, kind/client, kind/network, kind/question
