### ISSUE TITLE
How to reproduce the streisand.html again?

### ISSUE THREAD

**Issue by victorleejw** [jlund/streisand#969] opened 2017-09-28 16:30 UTC
I had a previous streisand made and just remade a new server. After the completion, i went to check the generated-docs folder and saw the old streisand.html file but not the new 1. Any command to reproduce the html file?

**Comment by cpu** [comment] 2017-09-29 00:29
@victorleejw Hmm, that's pretty odd! Can you provide more information?

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*

If the new server is still named "streisand" (the default) then the `generated-docs/streisand.html` file will have been *updated* with the new server information.

There isn't a way to "remake" the HTML file except by provisioning a brand new server.

**Comment by cpu** [comment] 2017-10-05 22:56
I'm going to close this issue since we don't have enough information to reproduce the problem. Please feel free to reopen if you are able to provide some more information. Thanks!

**Closed by cpu** 2017-10-05 22:56 UTC
Labels: kind/docs, kind/question, status/information-needed
