### ISSUE TITLE
digital ocean create droplet only recognizes the first ssh key name returned in the list

### ISSUE THREAD

**Issue by lfxc** [jlund/streisand#221] opened 2016-01-02 15:29 UTC
## FIle: streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml
- name: Retrieve the SSH key ID using the name that was provided
  shell: curl -s -X GET -H '{{ do_api_content_type_header }}' -H '{{ do_api_authorization_header }}' "https://api.digitalocean.com/v2/account/keys" | {{ ansible_python_interpreter }} -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [key for key in j["ssh_keys"] if key["name"]=="{{ do_ssh_name }}"][0]["id"]'
  register: do_ssh_key_id

**Comment by cpu** [comment] 2017-04-08 02:45
@lfxc Can you describe what the issue is? Does https://github.com/jlund/streisand/issues/239 accomplish what you need or is this a separate feature request?

It would be easier to review suggested Ansible role/task changes if you submitted them as a pull request so that there's an in-context diff to look at.

**Comment by cpu** [comment] 2017-05-24 00:05
I'm going to close this issue since it's still missing information and Ansible code changes should be submitted by PR - Thanks!

**Closed by cpu** 2017-05-24 00:05 UTC
Labels: area/ansible, area/ssh, kind/feature, provider/digital-ocean, status/information-needed
