### ISSUE TITLE
PGP Retry Errors, Failures after changing keyservers.

### ISSUE THREAD

**Issue by oneshoturdone** [jlund/streisand#899] opened 2017-08-25 02:45 UTC
### Expected behavior:
Successful installation after following the instructions to the letter.

### Actual Behavior:
Failure to verify key/repeated retries to obtain key.

### Steps to Reproduce:
I followed the instructions to the letter, but specifically for OpenConnect, and Libreswan, there were PGP retries, and even after modifying the keyservers and attempting to manually pull the keys, still no bones....I will admit I am trying to do this on Ubuntu 17 rather than 16, so there could be an issue there. I did have to change a package dependency for OpenConnect, however no matter what I do, I am simply unable to get these keys properly or perhaps signatures or files are invalid? I've managed to proceed by simply disabling both of these features manually in the playbook config files.

**Comment by alimakki** [comment] 2017-08-25 17:21
Hi @oneshoturdone,
We haven't tested on Ubuntu 17 so there's no guarantees there. 
That being said, Looking at the CI builds there doesn't seem to be any PGP retry errors so I'm guessing the issue is a sporadic one (it happens on occasion when I develop).

Have you tried to spin up a new instance on a supported version of Ubuntu to see if the problem reproduces itself?

**Comment by oneshoturdone** [comment] 2017-08-28 19:31
It works! That's what I get for being a fiend for bleeding edge.

**Comment by cpu** [comment] 2017-08-28 19:36
@oneshoturdone Glad you were able to provision a system successfully!! I'm going to close this issue for now since I don't think there's any action for us to take at the present time. Please re-open if you find you encounter the error again. Thanks!

**Closed by cpu** 2017-08-28 19:36 UTC
Labels: kind/question, status/information-needed
