### ISSUE TITLE
Shadowsocks: DNS Leak

### ISSUE THREAD

**Issue by NanoG6** [jlund/streisand#869] opened 2017-08-05 09:17 UTC
- Shadowrocket on iOS 10.3.3
- UDP relay enabled on client (and server, by streisand default config)
- If "Global Routing" set to "Config" in Shadowrocket DNS is leaking using provider's DNS resolver (TELKOM), not streisand server DNS resolver (OVH) as you can see below:
<img src=https://x.cdnd.xyz/G4T.png />
- Whereas if I set "Global Routing" to "Proxy", DNS resolver is correctly using streisand server DNS.. but doing so makes me unable to do Whatsapp Video Call. Call is ringing, but when I accept the call it stuck on connecting..
Anybody have same issue? Any help would be greatly appreciated!

**Comment by cpu** [comment] 2017-08-05 13:02
Hi @NanoG6,

Have you asked the Shadowrocket devs about this? I don't think there is anything to be done on the Streisand-side to fix this. It seems (at least to me, initially) to be a client issue.

**Comment by NanoG6** [comment] 2017-08-05 13:15
I haven't ask them, and tbh I think it's about shadowsocks settings (or bugs) because I have same issue using Potatso.

**Comment by cpu** [comment] 2017-08-05 13:23
@NanoG6 Ok, I'm interested in hearing what you learn. If there are Streisand settings or documentation that can be changed I'm definitely happy to dive in. I'm not able to replicate this with the Android Shadowsocks client. I'm going to close this issue for now since it isn't actionable but please feel free to add more discussion here if you learn more!

Thanks!

**Closed by cpu** 2017-08-05 13:23 UTC
Labels: area/shadowsocks

**Comment by Nyr** [comment] 2018-04-14 15:14
I know this is an old issue, but just found it via Google and this information can still be helpful for others in my situation: the problem is indeed client-side, I am not even using Streisand.

Shadowrocket is leaking DNS (and likely all UDP traffic, haven't checked) when using the "Config" option. If you configure DNS Override, you will no longer be using your ISP resolvers, but they are still routed outside of Shadowsocks.

Potatso 2 is an alternative client which supports custom configurations and doesn't have this issue as long as you enable UDP forwarding, but it has other issues.
