### ISSUE TITLE
Feature request: SoftEtherVPN.

### ISSUE THREAD

**Issue by chipitsine** [jlund/streisand#624] opened 2017-04-18 02:12 UTC
hello,

as I see, there's strong demand in bypassing chinese firewall.
SoftEtherVPN is known to bypass it.

probably I missed it, did you consider adding SoftEtherVPN to streisand ?

**Comment by strixaluco** [comment] 2017-05-03 07:09
@chipitsine, SoftEther VPN has been already requested in #140

**Comment by cpu** [comment] 2017-05-03 13:54
@strixaluco Thanks for noticing that.

Closing as a duplicate of #140

**Closed by cpu** 2017-05-03 13:54 UTC
Labels: kind/feature, kind/question
