### ISSUE TITLE
[question] default root password? 

### ISSUE THREAD

**Issue by juneyao** [jlund/streisand#358] opened 2016-07-05 16:47 UTC
i can only login as "forward". I can't do much without root. how to login AWS as root? when I enter su it asks for password (hitting enter does not do it)
also, aws ec2 instances are supposed to have ubuntu as default user. I can't log in as ubuntu neither, it asks for password.
Sorry if I missed something basic or obvious. Any help would be much appreciated.

**Comment by juneyao** [comment] 2016-07-06 19:54
google is not helping. I am using PuTTy on Windows and I can only ssh with "forward". ubuntu, root, ec2-user do not work
if i try "ubuntu" or "root", putty prompts: 
using username "ubuntu"
server refused our key. 
Disconnected: No supported authentication methods available (server sent: publickey)

openvpn is the only thing working on this aws streisand instance. I need to reinstall things, but "forward" does not have permissions 

any help would be much appreciated. thanks

**Comment by juneyao** [comment] 2016-07-06 19:54
google is not helping. I am using PuTTy on Windows and I can only ssh with "forward". ubuntu, root, ec2-user do not work
if i try "ubuntu" or "root", putty prompts: 
using username "ubuntu"
server refused our key. 
Disconnected: No supported authentication methods available (server sent: publickey)

openvpn is the only thing working on this aws streisand instance. I need to reinstall things, but "forward" does not have permissions 

any help would be much appreciated. thanks

**Comment by jlund** [comment] 2016-07-08 18:34
The `forward` user is unprivileged and has an entirely separate key than the one that would have been used to connect with root permissions to configure the server. This is by design.

You'll need to use the SSH key that is on the machine from which you initially ran Streisand. That key will allow you to connect as `ubuntu` on the EC2 instance, which is the same way that Ansible initially connected to the new server to run the Streisand playbook.

All of the services seem to be working for me on a new EC2 instance. Can you provide more detail about why only OpenVPN is working and what errors you are seeing?

**Comment by tobiasboyd** [comment] 2017-02-15 20:34
I can't seem to ssh in to a new Digital Ocean streisand instance as `ubuntu` I have the key used in setup specified in `.ssh/config` for the ip, but I'm getting `Permission denied (publickey).` errors. Am I missing something obvious?

**Comment by jlund** [comment] 2017-02-15 22:30
The username is `root` on new DigitalOcean servers instead of `ubuntu` (a la AWS).

**Comment by tobiasboyd** [comment] 2017-02-16 04:47
Thanks! I think that qualifies as "missing something obvious" ...

**Comment by cpu** [comment] 2017-05-20 02:06
I believe there's no outstanding questions in this thread - I'm going to close this issue. Thanks!

**Closed by cpu** 2017-05-20 02:06 UTC
Labels: area/provisioning, area/ssh, provider/amazon, status/information-needed
