### ISSUE TITLE
HTTPS connection to VPN server is "Not Secure" in Chrome

### ISSUE THREAD

**Issue by gmile** [jlund/streisand#637] opened 2017-04-23 09:23 UTC
Sorry if this is really dumb question, but after adding the certificate provided after installation & marking it as "Always trust" for SSL, the connection to VPN server by HTTPS is reported as not being secure in Chrome.

Is this considered OK, or am missing something?

![image](https://cloud.githubusercontent.com/assets/207112/25312236/1a430312-281d-11e7-8a59-bda7031b240f.png)

**Comment by chipitsine** [comment] 2017-04-23 12:05
do you access it by IP ? chrome does not like SSL over IP

**Comment by x8x** [comment] 2017-04-23 12:32
Have to agree that after the pain to manually add the cert, that error isn't very user friendly.
As the error says, this is due to missing `subject alternative name` in the cert.
Maybe that feature could be added to Streisand cert generation.
See here some references on how that could be done:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sssd-ldap-domain-ip.html
https://github.com/chef-cookbooks/openssl/issues/37
https://bowerstudios.com/node/1007

**Comment by cpu** [comment] 2017-04-23 14:37
I've captured the need for an IP type SAN for the self-signed gateway certificate here: https://github.com/jlund/streisand/issues/641

I have larger plans to rework the certificate generation that I hope to get to in the next few weeks that will address 641 and some other related problems.

**Comment by cpu** [comment] 2017-04-23 14:38
I'm going to close this issue in the meantime since it isn't actionable and the root cause of the error has been explained. Thanks for reporting! Please follow #641 for updates.

**Closed by cpu** 2017-04-23 14:38 UTC

**Comment by h-town** [comment] 2017-08-22 21:49
for those who land here and want to (temporarily) resolve this, see below link:

https://www.chromium.org/administrators/policy-list-3#EnableCommonNameFallbackForLocalAnchors

**Comment by nopdotcom** [comment] 2017-08-22 22:29
Thank you for the document pointer; it explains Chrome’s policy well.
