### ISSUE TITLE
UNREACHABLE on digital ocean - continually getting this error even though SSH is reachable

### ISSUE THREAD

**Issue by git-sgmoore** [jlund/streisand#242] opened 2016-02-03 02:06 UTC
PLAY [Provision the DigitalOcean Server] ***************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [genesis-digitalocean : Retrieve the SSH key ID using the name that was provided] ***
changed: [127.0.0.1]

TASK [genesis-digitalocean : Create the server. If this task fails with an "invalid region" error, then DigitalOcean is temporarily not allowing new 512MB Droplets to be provisioned in the selected region. You can either try the same region again later, or choose a different location.] ***
changed: [127.0.0.1]

TASK [genesis-digitalocean : Retrieve the IP address of the new Droplet] *******
FAILED - RETRYING: TASK: genesis-digitalocean : Retrieve the IP address of the new Droplet (9 retries left). Result was: {u'changed': True, u'end': u'2016-02-02 21:02:06.316012', 'failed': True, u'stdout': u'', u'cmd': u'curl -s -X GET -H \'Content-Type: application/json\' -H \'Authorization: Bearer [filtered]\' "https://api.digitalocean.com/v2/droplets/10732781" | python -c \'import json; import sys; j = json.loads(sys.stdin.read()); print j["droplet"]["networks"]["v4"][0]["ip_address"]\'', u'rc': 1, u'start': u'2016-02-02 21:02:05.865401', u'stderr': u'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nIndexError: list index out of range', u'delta': u'0:00:00.450611', 'invocation': {'module_name': u'command', u'module_args': {u'creates': None, u'executable': None, u'chdir': None, u'_raw_params': u'curl -s -X GET -H \'Content-Type: application/json\' -H \'Authorization: Bearer [filtered]\' "https://api.digitalocean.com/v2/droplets/10732781" | python -c \'import json; import sys; j = json.loads(sys.stdin.read()); print j["droplet"]["networks"]["v4"][0]["ip_address"]\'', u'removes': None, u'warn': False, u'_uses_shell': True}}, 'stdout_lines': [], u'warnings': []}
changed: [127.0.0.1]

TASK [genesis-digitalocean : Wait until the server has finished booting and OpenSSH is accepting connections] ***
ok: [127.0.0.1]

TASK [genesis-digitalocean : Create the in-memory inventory group] *************
changed: [127.0.0.1]

TASK [genesis-digitalocean : Set the streisand_ipv4_address variable] **********
ok: [127.0.0.1]

TASK [genesis-digitalocean : Set the streisand_server_name variable] ***********
ok: [127.0.0.1]

PLAY [Configure the Server and install required software] **********************

TASK [setup] *******************************************************************
fatal: [104.236.174.223]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}

PLAY RECAP *********************************************************************
104.236.174.223            : ok=0    changed=0    unreachable=1    failed=0   
127.0.0.1                  : ok=8    changed=4    unreachable=0    failed=0

**Comment by jlund** [comment] 2016-02-03 04:51
Dupe of #237.

**Closed by jlund** 2016-02-03 04:51 UTC

**Comment by jlund** [comment] 2016-02-03 04:53
@git-sgmoore: You'll want to revoke your DigitalOcean API key. I have edited your message above to remove it, but it still would have gone out via email notifications to individuals who are following this repository.

Thanks for the report. I'm looking into this now.
