### ISSUE TITLE
Install fails at WireGuard install step (linode, ubuntu 16.04)

### ISSUE THREAD

**Issue by clairity** [jlund/streisand#757] opened 2017-06-24 04:53 UTC
### Expected behavior:
smooth install of streisand

### Actual Behavior:
received this error:
```
TASK [wireguard : Install the WireGuard packages] *****************************************
failed: [xx.xx.xx.xx] (item=[u'linux-headers-4.9.15-x86_64-linode81', 
u'linux-headers-generic', u'wireguard-dkms', u'wireguard-tools']) => {"failed": true, 
"item": ["linux-headers-4.9.15-x86_64-linode81", "linux-headers-generic", "wireguard-dkms",
"wireguard-tools"], "msg": "No package matching 'linux-headers-4.9.15-x86_64-linode81' 
is available"}
```
everything before this seems to install ok.

### Steps to Reproduce:
1. run `./streisand`
2. choose provider (Linode), region (Fremont), and accept default name (streisand)
3. provide linode API key
4. enter ssh key passphrase
5. wait 7-8 minutes

**Comment by alimakki** [comment] 2017-06-24 13:25
Hi @clairity, definitely looks like an issue (and was able to reproduce it locally), my suspicion is a change on Linode's end that has caused the breakage.

We will take a look into this and follow up in due course :)

**Comment by cpu** [comment] 2017-06-24 13:36
In the meantime you shouldn't have this problem if you choose a different provider (DigitalOcean, etc).

**Comment by clairity** [comment] 2017-06-24 17:13
thanks! although i'd like to get streisand up and running as soon as possible, it's not an urgency, so i will wait for the fix for linode.

**Comment by yotokan** [comment] 2017-06-24 20:09
maybe something to do with one of their boxes pointing to package server via ipv6? 
answer for my ubuntu install was at https://serverfault.com/questions/93717/setting-ipv4-as-preferred-protocol-over-ipv6, maybe one of the routes at the host is set weird?

**Comment by alimakki** [comment] 2017-06-24 23:18
@clairity, I just wanted to let you know that I have filed a support ticket with Linode and working with them to better help identify the source of the issue.

**Comment by alimakki** [comment] 2017-06-24 23:49
Got a follow up from Linode:

>Hello Ali,
>
>I was able to confirm that only "ISXEN":1 versions of pv-grub are listed by the API. I'm really sorry about that and I'll be escalating this to our administrators to see what happened to the KVM GRUB2 kernel option in the API.
>
>This might take a couple of days but we'll stay on top of it for you. Thanks for your patience as we work to find out what the fire happened to KVM GRUB2.
>
>We'll update this ticket as soon as we know more.

**Comment by alimakki** [comment] 2017-06-26 23:16
@clairity The fix is in place, just grab the latest master and have at it!

**Closed** 2017-06-26 23:15 UTC
Labels: area/provisioning, area/wireguard, kind/bug, provider/linode, status/help-wanted

**Comment by clairity** [comment] 2017-06-27 01:12
yay, thank you!

**Comment by HeaTeR** [comment] 2017-06-29 10:56
`
TASK [wireguard : Install the WireGuard packages] ************************************************************************************************
failed: [127.0.0.1] (item=[u'linux-headers-4.9.15-x86_64-linode81', u'linux-headers-generic', u'wireguard-dkms', u'wireguard-tools']) => {"failed": true, "item": ["linux-headers-4.9.15-x86_64-linode81", "linux-headers-generic", "wireguard-dkms", "wireguard-tools"], "msg": "No package matching 'linux-headers-4.9.15-x86_64-linode81' is available"}

`

on linode ubuntu 16.04.2 LTS, GNU/Linux 4.9.15-x86_64-linode81 x86_64

**Comment by clairity** [comment] 2017-07-02 04:38
i can confirm that, after this fix, i was able to get streisand up and running on my linode instance. thanks!

**Comment by cpu** [comment] 2017-07-02 14:56
@HeaTeR What is the revision of your Streisand checkout?

**Comment by hiddeco** [comment] 2017-09-22 10:14
Experiencing the same issue while provisioning an existing Scaleway server. I'm on the latest `master` (https://github.com/jlund/streisand/tree/40b3b1a695ddc77055203784b297378b6f9e73c0).

**Comment by cpu** [comment] 2017-09-22 12:55
@hiddeco Please don't comment on closed issues when you have a new issue. A new issue with what you're experiencing would be best.

In this case unfortunately Scaleway is 100% unsupported. If you search the issues there are lots of others related to Scaleway and their custom kernel. I would recommend using a supported provider, we don't have the resources to try and make Streisand work with scaleway.

**Comment by nopdotcom** [comment] 2017-09-22 17:19
Do we want an explicit list of "our software has had serious compatibility problems with the following providers, and we are hoping for pull requests: Scaleway, rpi, uh I forget what else"?
