### ISSUE TITLE
streisand on vultr

### ISSUE THREAD

**Issue by lodgnewt** [jlund/streisand#806] opened 2017-07-14 05:05 UTC
run straisand on vultr host and get error in the end

 ```
[streisand-gateway : Success!]
Server setup is complete. The `vpn.html` instructions file in the generated-docs folder is ready to give to friends, family members, and fellow activists. Press Enter to continue.:
ok: [xx.xx.xx.xx]

TASK [streisand-gateway : Attempt to open the instructions on Linux (if applicable). Errors in this task are ignored because the `xdg-open` command is not always available.] ***
fatal: [xx.xx.xx.xx]: FAILED! => {"failed": true, "msg": "The conditional check 'hostvars['127.0.0.1']['ansible_system'] == \"Linux\"' failed. The error was: error while evaluating conditional (hostvars['127.0.0.1']['ansible_system'] == \"Linux\"): 'dict object' has no attribute 'ansible_system'\n\nThe error appears to have been in '/home/noname/streisand/streisand/playbooks/roles/streisand-gateway/tasks/main.yml': line 199, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n
- name: Attempt to open the instructions on Linux (if applicable). Errors in this task are ignored because the `xdg-open` command is not always available.\n          ^ here\n"}
...ignoring

TASK [streisand-gateway : Open the instructions on OS X (if applicable)] ****************************************

fatal: [xx.xx.xx.xx]: FAILED! => {"failed": true, "msg": "The conditional check 'hostvars['127.0.0.1']['ansible_system'] == \"Darwin\"' failed. The error was: error while evaluating conditional (hostvars['127.0.0.1']['ansible_system'] == \"Darwin\"): 'dict object' has no attribute 'ansible_system'\n\nThe error appears to have been in '/home/noname/streisand/streisand/playbooks/roles/streisand-gateway/tasks/main.yml': line 205, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n
  - name: Open the instructions on OS X (if applicable)\n          ^ here\n"}
        to retry, use: --limit @/home/noname/streisand/streisand/playbooks/existing-server.retry

PLAY RECAP ******************************************************************************************************

xx.xx.xx.xx              : ok=340  changed=294  unreachable=0    failed=2
```

**Comment by cpu** [comment] 2017-07-14 12:11
Hi @lodgnewt,

This is a duplicate of https://github.com/jlund/streisand/issues/739 Please follow that issue.

As a note this task just attempts to open the generated docs in your Ansible machine's browser. In this case since the Ansible machine is a headless Vultr server it would have been skipped if the bug hadn't prevented it so there's no effective difference in your Streisand system. Apologies for the bug!

**Closed by cpu** 2017-07-14 12:11 UTC
