### ISSUE TITLE
[GCE] Unable to restart service xl2tpd

### ISSUE THREAD

**Issue by pchaganti** [jlund/streisand#568] opened 2017-04-02 19:02 UTC
Running the latest version on GCE. Getting this error:

```
RUNNING HANDLER [l2tp-ipsec : Restart xl2tpd] **********************************
fatal: [35.185.52.148]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service xl2tpd: Job for xl2tpd.service failed because the control process exited with error code. See \"systemctl status xl2tpd.service\" and \"journalctl -xe\" for details.\n"}
```

Anyone have any pointers?

thanks

**Comment by cpu** [comment] 2017-04-07 00:57
> See \"systemctl status xl2tpd.service\" and \"journalctl -xe\" for details.\n"}

Can you provide the output from both of these? It will likely help others troubleshoot the problem!

**Comment by pchaganti** [comment] 2017-04-07 13:13
Could not SSH into the launched server.  Unable to run these commands. 

Switched to using AWS. Worked fine for me.

**Comment by cpu** [comment] 2017-04-07 14:01
> Could not SSH into the launched server. Unable to run these commands.

Ok, thanks anyway! Glad to hear you were able to find a work-around.

@CorbanR - I see you assigned this to yourself (Thanks!!). Do you think you can reproduce with the information available?

**Comment by CorbanR** [comment] 2017-04-09 00:20
@cpu Yeah, ill test it out this evening! Also thank for doing all this ticket triage dude!

**Comment by tedd4u** [comment] 2017-04-09 01:06
I saw the same error today with latest code on GCP. Also couldn't ssh in. And https port wasn't responding. I already nuked the server but I'm happy to assist in any way. Have set up Streisand 3-4 times before on GCP with no problems. Last time was about March 24th.

**Comment by CorbanR** [comment] 2017-04-09 02:45
I didn't run into the same problem when testing. I assume it was just a fluke.. Having said, that if two people are having the same issue, it makes me think it's more than just a fluke
I tried with the most recent version of Ansible `2.2.2.0`, and previous `2.2.1.0`, I am also using a fairly recent version of `apache-libcloud`

@tedd4u @pchaganti can you provide me with the following information? 

OS: OSX, Ubuntu, etc.
Ansible version: `ansible --version`
apache-libcloud ` pip list | grep -i apache (assuming you used pip)`


As far as having problems when trying to ssh on the instance, ensure you are using the correct ssh key, if trying to login as root, make sure you're specifying the right user. `ssh ubuntu@<server_ip>`

**Comment by tedd4u** [comment] 2017-04-09 05:30
Thank you @CorbanR 

I'm using Mac OS X 10.11.6 (El Capitan) (15G1421). 
On the off chance it's a region-specific problem, I used GCP Western US (Oregon A).

Here are the details.

```
$ uname -a
Darwin imac.local 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
$ ansible --version
ansible 2.2.1.0
  config file = /Users/*****/dev/streisand/ansible.cfg
  configured module search path = Default w/o overrides
$  pip list | grep -i apache
apache-libcloud (1.3.0)
$ python -V
Python 2.7.13
```

I will update both Ansible and libcloud, try again, and report back.

**Comment by pchaganti** [comment] 2017-04-09 12:54
Using Mac OSX Sierra 10.12.1

```
$ uname -a
Darwin elysium.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64

$ ansible --version
ansible 2.2.2.0
  config file = /Users/*****/dev/streisand/ansible.cfg
  configured module search path = Default w/o overrides

$  pip list | grep -i apache
apache-libcloud (1.5.0)

$ python -V
Python 2.7.13
```

**Comment by tedd4u** [comment] 2017-04-09 15:06
I updated to Ansible 2.2.2.0 annd apache-libcloud 1.5.0 and saw the same result. I ssh'd in and get this output (below). 

I don't actually use l2tp but what is also wrong is that there's nothing running on port 443.

```
RUNNING HANDLER [l2tp-ipsec : Restart xl2tpd] **********************************
fatal: [104.196.241.224]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service xl2tpd: Job for xl2tpd.service failed because the control process exited with error code. See \"systemctl status xl2tpd.service\" and \"journalctl -xe\" for details.\n"}

RUNNING HANDLER [dnsmasq : Restart dnsmasq] ************************************

RUNNING HANDLER [openvpn : Restart OpenVPN] ************************************

RUNNING HANDLER [stunnel : Restart stunnel] ************************************

RUNNING HANDLER [shadowsocks : Restart shadowsocks-libev] **********************

RUNNING HANDLER [ssh : Restart SSH] ********************************************

RUNNING HANDLER [tinyproxy : Restart Tinyproxy] ********************************

RUNNING HANDLER [sslh : Restart sslh] ******************************************

RUNNING HANDLER [monit : Restart Monit] ****************************************

RUNNING HANDLER [nginx : Restart Nginx] ****************************************
	to retry, use: --limit @/Users/millers/dev/streisand/playbooks/google.retry

PLAY RECAP *********************************************************************
104.196.241.224            : ok=283  changed=255  unreachable=0    failed=1   
localhost                  : ok=20   changed=12   unreachable=0    failed=0   
```

```
$ ps axu | grep ssl
ubuntu   23191  0.0  0.1  12944  1084 pts/0    S+   15:03   0:00 grep --color=auto ssl
$ ps axu | grep ngi
ubuntu   23194  0.0  0.1  12944   936 pts/0    S+   15:05   0:00 grep --color=auto ngi
```

```
$ telnet localhost 443
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

```
$ systemctl status xl2tpd.service
● xl2tpd.service - LSB: layer 2 tunelling protocol daemon
   Loaded: loaded (/etc/init.d/xl2tpd; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-04-09 06:25:57 UTC; 8h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 22901 ExecStop=/etc/init.d/xl2tpd stop (code=exited, status=0/SUCCESS)
  Process: 22907 ExecStart=/etc/init.d/xl2tpd start (code=exited, status=1/FAILURE)
    Tasks: 0
   Memory: 528.0K
      CPU: 3ms

Apr 09 06:25:57 streisand0417-2 systemd[1]: Stopped LSB: layer 2 tunelling protocol daemon.
Apr 09 06:25:57 streisand0417-2 systemd[1]: Starting LSB: layer 2 tunelling protocol daemon...
Apr 09 06:25:57 streisand0417-2 xl2tpd[22907]: Starting xl2tpd:
Apr 09 06:25:57 streisand0417-2 systemd[1]: xl2tpd.service: Control process exited, code=exited status=1
Apr 09 06:25:57 streisand0417-2 systemd[1]: Failed to start LSB: layer 2 tunelling protocol daemon.
Apr 09 06:25:57 streisand0417-2 systemd[1]: xl2tpd.service: Unit entered failed state.
Apr 09 06:25:57 streisand0417-2 systemd[1]: xl2tpd.service: Failed with result 'exit-code'.
Apr 09 06:25:57 streisand0417-2 xl2tpd[23651]: death_handler: Fatal signal 15 received
```

```
$ journalctl -xe
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
Apr 09 14:47:31 streisand0417-2 systemd[23099]: Reached target Sockets.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
Apr 09 14:47:31 streisand0417-2 systemd[23099]: Reached target Timers.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
Apr 09 14:47:31 streisand0417-2 systemd[23099]: Reached target Basic System.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
Apr 09 14:47:31 streisand0417-2 systemd[23099]: Reached target Default.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
Apr 09 14:47:31 streisand0417-2 systemd[23099]: Startup finished in 24ms.
-- Subject: System start-up is now complete
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- All system services necessary queued for starting at boot have been
-- successfully started. Note that this does not mean that the machine is
-- now idle as services might still be busy with completing start-up.
-- 
-- Kernel start-up required KERNEL_USEC microseconds.
-- 
-- Initial RAM disk start-up required INITRD_USEC microseconds.
-- 
-- Userspace start-up required 24484 microseconds.
Apr 09 14:47:31 streisand0417-2 systemd[1]: Started User Manager for UID 1000.
-- Subject: Unit user@1000.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit user@1000.service has finished starting up.
-- 
-- The start-up result is done.
```

**Comment by pchaganti** [comment] 2017-04-09 15:12
Another workaround for GCE for now. If you dont use l2tp, comment out the restart in the playbook and everything else starts up and works fine.

**Comment by CorbanR** [comment] 2017-04-09 18:01
Is there any possibility that you are re-using a previously created GCE network? Streisand on GCE creates a Streisand network, as well as an Instance. I would think reusing the network should be fine.. but maybe that's causing the problem. 

Ill test in Western US (Oregon A), as well as reusing a previously Streisand created network(I have always deleted both the instance and network when I use / clean up Streisand in GCE.

**Comment by CorbanR** [comment] 2017-04-09 23:57
I was finally able to reproduce the issue. I tried using  Western US (Oregon A) and saw the same error. I then tried again adding some verbosity`-vvvv` for debugging purposes, and did NOT have the same issue... I then tried temporarily increasing the instance size (because testing on an f1-micro was SLOW) and again, didn't see the issue. 😞 This seems to be very intermittent and is causing me some grief.

**Comment by tedd4u** [comment] 2017-04-10 01:55
I did as @pchaganti suggested and commented the xl2tpd restart out and ... it works. Everything is up and running on :443 and the script completes without errors. Since I don't use l2tp that's not an issue for me, just an inconvenience. Hoping to get the -$10 benefit of f1-micro over g1-small. I have no idea why this would be but I really don't know anything about how Ansible works (thus my love for Streisand!).

**Comment by CorbanR** [comment] 2017-04-10 05:58
@tedd4u @pchaganti I would be grateful if you could try one more time with this commit https://github.com/jlund/streisand/pull/593 I'm still not 100% sure why, but there appears to be a race condition of some sort when ansible tries to restart that particular service (that's my guess anyway), it was hard to pin down because I couldn't get the error on ever run. However, adding the

```- name: Restart xl2tpd
  service:
    name: xl2tpd
    state: restarted
  register: xl2tpd_restart_result
  until: xl2tpd_restart_result|success
  retries: 3
  delay: 5```

to the restart task. I tested at least 5 different times, and when I did encounter the error, the retry logic seemed to work. . Let me know if that fixes it for you.

**Comment by pchaganti** [comment] 2017-04-10 11:08
This seems to work for me. I was able to start Streisand in GCE Eastern region with l2tp.

thanks!

**Comment by zoof** [comment] 2017-04-10 19:50
I just started a Streisand instance and ran into the same problem, maybe 5 hours ago?  The web interface is working but I can't ssh into the box, either from the command line or using the GCE browser terminal.  An f1-micro instance on us-east1-c.

**Comment by tedd4u** [comment] 2017-04-10 21:39
@zoof two notes - 1) I don't think #593 has been committed to master yet, you might try applying it locally or switching to CorbanR:master. 2) Re SSH'ing in - make sure to use "ssh ubuntu@<server_ip>". Needs to be user ubuntu.

**Comment by zoof** [comment] 2017-04-10 22:22
Thanks -- 2) "ssh ubuntu@<server_ip>" didn't work either.  I can't even ssh into the server via CGE's web interface.  1) Given that I can't access the server, I can't try any of these options.

Will the eventual automatic update fix this?  Or will I need to wait until #593 has been committed to spin up a new instance?

**Comment by zoof** [comment] 2017-04-11 03:26
So I am able to ssh in through Google Cloud Shell.  For what it is worth, xl2tpd is running:

    $ systemctl status xl2tpd.service 
    ● xl2tpd.service - LSB: layer 2 tunelling protocol daemon
       Loaded: loaded (/etc/init.d/xl2tpd; bad; vendor preset: enabled)
       Active: active (running) since Mon 2017-04-10 16:00:27 UTC; 11h ago
         Docs: man:systemd-sysv-generator(8)
      Process: 2933 ExecStop=/etc/init.d/xl2tpd stop (code=exited, status=0/SUCCESS)
      Process: 2940 ExecStart=/etc/init.d/xl2tpd start (code=exited, status=0/SUCCESS)
        Tasks: 1
       Memory: 732.0K
          CPU: 132ms
       CGroup: /system.slice/xl2tpd.service
               └─2956 /usr/sbin/xl2tpd

but I'm still unable to ssh into the instance without going through the Google Cloud Shell.  I.e., neither the command line or directly through the control panel -- not sure what the difference between "Open in browser window" and `gcloud compute --project "pvz2-1062" ssh --zone "us-east1-c" "streisand"` is but the latter works and the former does not.

**Comment by CorbanR** [comment] 2017-04-12 04:45
As far as this particular ticket goes I think the original issue has been resolved. 

@zoof mind opening up new ticket regarding the ssh problems?.

**Comment by tedd4u** [comment] 2017-04-12 04:51
Thank you @CorbanR for solving this.

**Comment by zoof** [comment] 2017-04-12 11:11
@CorbanR Done (#599) -- thank you!

**Closed** 2017-04-14 01:40 UTC
Labels: area/l2tp, kind/question, provider/gce
