### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by zzztimbo** [jlund/streisand#252] opened 2016-02-16 18:36 UTC
Are there any plans to add user management? Streisand might be good for startups?

**Comment by cpu** [comment] 2017-06-16 21:40
There are no plans presently. I'm open to the idea but there are no PRs to review ;-) and I think modularization and better testing infrastructure are higher priority.

This feature request is a duplicate of https://github.com/jlund/streisand/pull/724 and so I'm going to close it to centralize further discussion/planning on #724. Thanks!

**Closed by cpu** 2017-06-16 21:40 UTC
Labels: kind/feature, kind/question
