### ISSUE TITLE
Add secure DNS server service

### ISSUE THREAD

**Issue by BYK** [jlund/streisand#68] opened 2014-09-04 15:20 UTC
I think it would be nice to have a secure DNS server implementation such as DNSCurve.

**Comment by Bretos** [comment] 2015-01-25 11:15
I see the need to use a DNS-crypt powered dns server(or proxy) with SSL over TCP when connecting to the Internet from a strictly restricted network which allows only for http/https connections and has local DNS server that logs both the query and source IP/MAC and/or doesn't allow resolving selected domains. If streisand is about privacy and security, my guess is it should support personal/private DNS resolver. I think something similar to [this](https://wiki.archlinux.org/index.php/DNSCrypt) with dnsmasq should be enough.

 However this issue is quiet old, it is not closed and since I decided to post here, instead of creating a new one.

**Comment by theodorerambert** [comment] 2015-07-20 21:35
DNSCrypt is a stable project with several DNS providers. All queries go over port 443 and are encrypted. This should replace dnsmasq.


I've used the script below on my OpenVPN VPS running Debian 7
https://github.com/simonclausen/dnscrypt-autoinstall

**Comment by cpu** [comment] 2017-06-16 21:53
https://github.com/jlund/streisand/issues/272 is a duplicate of this pre-existing issue but the discussion on 272 seems more complete. I'm going to close this issue and encourage interested folks to follow 272 instead.

**Closed by cpu** 2017-06-16 21:53 UTC
Labels: area/dns, kind/client, kind/feature
