### ISSUE TITLE
Error:The Private Key for this Client Certificate is missing or invalid.

### ISSUE THREAD

**Issue by wdonno** [jlund/streisand#579] opened 2017-04-07 00:38 UTC
Multiple tries setting up on AWS.  The generated certificate causes the subject error when loading into chrome (and elsewhere).  Can connect via OpenVPN from an android device (so overall Streisand VPN is working).  Can someone point me to code to regenerate the certificate or give other suggestion to correct?  Many thanks for any help!

**Comment by cpu** [comment] 2017-04-07 00:42
Hi @wdonno 

> The generated certificate causes the subject error when loading into chrome (and elsewhere). 

The gateway HTTPS certificate is self-signed and will always generate a warning interstitial in Chrome and other browsers unless you manually trust it. 

Have you tried following the "SSL Certificate Installation" steps from the generated documentation?

**Comment by wdonno** [comment] 2017-04-07 01:23
Thank you for the feedback.  While waiting, I was able to use the certificate on OS-X, having followed the directions.  However I still can not get it to work on Chrome, the browser, on any platform.  No option to trust is offered.
(Also, cannot get find a way to connect on a chromebook.)

**Comment by nickolasclarke** [comment] 2017-04-29 04:40
@wdonno on win10 if I import the key included in the "how to connect to gateway" instructions, I get the same error, but it still allows me to proceed.

**Comment by cpu** [comment] 2017-06-16 22:53
I believe #641 is the root cause of this error. I'm going to close this issue to centralize discussion there. I also have a WIP branch that I will eventually find time to merge with a fix. Thanks!

**Closed by cpu** 2017-06-16 22:53 UTC
Labels: area/tls, kind/question
