### ISSUE TITLE
Concurrent WireGuard Clients

### ISSUE THREAD

**Issue by ddvzlnz** [jlund/streisand#498] opened 2017-02-02 18:41 UTC
This is more of a question than in issue.  I just spun up the latest to check out WireGuard.  Silly fast, thank you.  I was wondering though, there seems to be only one client configured (and five for all of the others).  Can multiple clients use the one config file?  If they can is that preferable to multiple configurations?   I'm just digging into the WireGuard Docs tonight, thought I'd ask first.

Thanks

**Comment by zx2c4** [comment] 2017-03-30 00:02
One client, one config.

Streisand supposedly generates 5 wireguard configs though, no?

**Comment by cpu** [comment] 2017-05-20 13:34
> Streisand supposedly generates 5 wireguard configs though, no?

It is only generating one right now. I opened https://github.com/jlund/streisand/issues/693 to create 4 more and will close this issue since it's working as intended (one client per one config).

Thanks!

**Closed by cpu** 2017-05-20 13:34 UTC
Labels: area/wireguard, kind/client, kind/question
