### ISSUE TITLE
Create two WiFi networks on OpenWRT

### ISSUE THREAD

**Issue by tymmej** [jlund/streisand#441] opened 2016-11-22 06:28 UTC
On https://github.com/jlund/streisand/wiki/Setting-an-OpenWrt-Router-as-OpenVPN-Client there's
> TODO: Add necessary code to have one WiFi Network with VPN and other without (in a few days)...

Does anyone know how to do it?

**Comment by jamesspi** [comment] 2016-11-22 14:24
@tymmej Yes - I've been meaning to post instructions for ages, haven't found the time yet.

**Comment by tymmej** [comment] 2016-11-22 16:19
Are there other tutorials how to achieve it?
I couldn't find anything.

**Comment by braian87b** [comment] 2017-02-06 01:25
Hi, Sorry link changed... now is on: https://github.com/jlund/streisand/wiki/Setting-an-OpenWrt-Based-Router-as-OpenVPN-Client

I am on working on it with @jamesspi...

**Comment by cpu** [comment] 2017-04-07 23:17
@braian87b Were you and @jamesspi able to update the docs to clarify this? Should the issue remain open?

**Comment by tymmej** [comment] 2017-04-08 15:23
I'm still looking at wiki with hope

**Comment by jamesspi** [comment] 2017-04-08 15:25
Sorry guys, I completely dropped the ball on this. @brian87b and @cpu, I'll have a full tutorial next week - promise!

**Comment by cpu** [comment] 2017-04-08 15:44
@jamesspi Thanks for the update!

**Comment by jamesspi** [comment] 2017-04-09 10:04
@braian87b - Shall I just append this to your wiki, or would you prefer if I create a new one?

**Comment by braian87b** [comment] 2017-04-09 12:54
@jamesspi Mh, to avoid confusion of too-long tutorial add it to a new page with similar title and you could add "(cont.)" "part 2" or even better: "additional config for multiple..." that should be fine, Thanks!!!

**Comment by jamesspi** [comment] 2017-04-09 12:59
@braian87b Sure thing!

**Comment by braian87b** [comment] 2017-05-03 01:11
@jamesspi do you need help? just let me know! 👍

**Comment by jamesspi** [comment] 2017-05-03 07:35
Hey @braian87b - I'm actually half way through it. The problem is I recently had to scrap my OpenWRT instance and am working off the backup files. I've been dragging this for months and I feel like a jerk now! Will aim to finish ASAP.

**Comment by cpu** [comment] 2017-07-23 22:28
I'm going to close this issue for now. I think OpenWRT instructions are likely out of scope for the project for now. I'm willing to reconsider if there is a PR to review but we should move the discussion to a new thread on the [streisand discussions repo](https://github.com/jlund/streisand-discussions)

**Closed by cpu** 2017-07-23 22:28 UTC
Labels: area/openvpn, kind/client, kind/docs, kind/question
