### ISSUE TITLE
What's Alert_cpu_threshold?

### ISSUE THREAD

**Issue by HeaTeR** [jlund/streisand#771] opened 2017-06-29 09:52 UTC
### Expected behavior:
Should create linode instance and log in. but failed.
### Actual Behavior:

```
PLAY [Provision the Linode Server] ***************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [genesis-linode : Get the default SSH key] **************************************************************************************************
changed: [localhost]

TASK [genesis-linode : Create the server] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Alert_cpu_threshold must be between 0 and 2000."}
	to retry, use: --limit @/Users/linzheming/Documents/streisand/playbooks/linode.retry

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   


```
### Steps to Reproduce:
1. run ./streisand

**Comment by cpu** [comment] 2017-06-29 20:14
Hi @HeaTeR,

Sorry to hear you ran into this error. This issue is actually a duplicate of https://github.com/jlund/streisand/issues/626, where another user ran into this error from OSX as well.

Unfortunately I don't have any recommended solutions & I don't have any OSX machines available personally to help try and triage this issue. I recommend you follow #626 and hopefully another maintainer or a member of the community will be able to solve the problem there.

Thanks!

**Closed by cpu** 2017-06-29 20:14 UTC
Labels: area/ansible, kind/bug, kind/client, provider/linode

**Comment by HougeLangley** [comment] 2017-07-31 13:51
Thank you. I have to try other way.
