### ISSUE TITLE
Fails to convert the OpenSSH key into a PuTTY .ppk on Raspbian

### ISSUE THREAD

**Issue by Couto** [jlund/streisand#47] opened 2014-08-02 23:48 UTC
I'm quite newbie when it comes to Ansible so I might be doing something wrong.

I always get this error message, when trying to deploy streisand on a Raspberry Pi running a clean image of raspbian.

```
TASK: [ssh | Convert the OpenSSH key into a PuTTY .ppk] ***********************
<192.168.2.4> ESTABLISH CONNECTION FOR USER: pi
<192.168.2.4> REMOTE_MODULE command puttygen /home/forward/.ssh/id_rsa -o /var/www/streisand/ssh/streisand_rsa.ppk creates=/var/www/streisand/ssh/streisand_rsa.ppk
<192.168.2.4> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/couto/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=pi', '-o', 'ConnectTimeout=10', '192.168.2.4', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1407023324.51-14077763642857 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1407023324.51-14077763642857 && echo $HOME/.ansible/tmp/ansible-tmp-1407023324.51-14077763642857'"]
<192.168.2.4> PUT /var/folders/gq/yqpcdpxs2sj54yxchblrp2hw0000gn/T/tmpouBaKa TO /home/pi/.ansible/tmp/ansible-tmp-1407023324.51-14077763642857/command
<192.168.2.4> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/couto/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '
-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=pi', '-o', 'ConnectTimeout=10', '192.168.2.4', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=vmxzc
urxyullqgdyklckecdkxdcqqbex] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-vmxzcurxyullqgdyklckecdkxdcqqbex; LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /home/pi/.ansible/tmp/ansible-tmp-1407023324.51-14077763642857/command;
 rm -rf /home/pi/.ansible/tmp/ansible-tmp-1407023324.51-14077763642857/ >/dev/null 2>&1\'"\'"\'\'']
failed: [192.168.2.4] => {"changed": true, "cmd": ["puttygen", "/home/forward/.ssh/id_rsa", "-o", "/var/www/streisand/ssh/streisand_rsa.ppk"], "delta": "0:00:00.039177", "end": "2014-08-02 23:48:45.630859", "rc": -11, "start": "2014-08-02 23:48:
45.591682"}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/couto/streisand.retry

192.168.2.4                : ok=81   changed=24   unreachable=0    failed=1
```

If I disable that specific task, it ends up failing when deploying the tor bridge, and if I disable the tor bridge, it ends up failing on nginx, not sure if they're related.

**Comment by cpu** [comment] 2017-04-08 15:37
The root cause of this issue was an unsupported operating system. I think the discussion has fallen off and it's time to close this issue. A potential follow-up would be to file a new issue describing a feature request to support Raspbian & the raspberry pi platform. Thanks!

**Closed by cpu** 2017-04-08 15:37 UTC
Labels: area/ansible, area/ssh, kind/question
