### ISSUE TITLE
AWS - change instance type - stopped responding

### ISSUE THREAD

**Issue by gladiator26** [jlund/streisand#396] opened 2016-09-05 23:09 UTC
Everything installs fine but when I change the instance type from the free t2.micro to a higher tier and restart the instance, I am not able to connect any longer. I deleted the instance and re-installed Streisand, but same issue occurred again.

Any chance anyone knows how to fix this? or how to choose the instance type when installing Streisand (I need to install it on t2.medium.

Many thanks.

**Comment by cyrrill** [comment] 2016-09-08 20:54
@gladiator26 Have a look in:
https://github.com/jlund/streisand/blob/15993fe27533515c38c1f9619b7d19ca92983e17/playbooks/roles/genesis-amazon/defaults/main.yml#L2

**Comment by gladiator26** [comment] 2016-09-08 22:00
Thank you Cyrrill for your reply. I am at the very beginning learning stage of github, I opened the  link yo provided but it did not understand what to do exactly. Any chance you can elaborate a little? if this is not meant to be for newbies and you don't have time to waste on me I totally understand and thank you anyways :)

Thanks again

**Comment by cyrrill** [comment] 2016-09-08 22:42
In your checked out local repository (on your laptop), find this file:
```/playbooks/roles/genesis-amazon/defaults/main.yml```

open it in a text editor, and change the value inside the quotes to the EC2 instance type you need:

aws_instance_type: "t2.micro"  -->  aws_instance_type: "t2.medium"

Save the file, exit, and now you can run Streinsand for a new machine, and it will be of medium type instead of micro.

**Comment by gladiator26** [comment] 2016-09-08 23:25
Made the change (from t2.micro to t2.medium) launched and got this error:

Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Google
  4. Linode
  5. Rackspace
: 1


ERROR! Syntax Error while loading YAML.


The error appears to have been in '/Users/gladiator/streisand/playbooks/roles/genesis-amazon/defaults/main.yml': line 4, column 17, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Search AMIs owned by this owner. This is the Amazon owner ID.
aws_ami_owner: "099720109477"
                ^ here

**Comment by cyrrill** [comment] 2016-09-09 00:08
Can you paste the contents of the file?

**Comment by gladiator26** [comment] 2016-09-09 00:22
---
aws_instance_type: "t2.micro"
# Search AMIs owned by this owner. This is the Amazon owner ID.
aws_ami_owner: "099720109477"
# Find AMIs matching this name
aws_ami_name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"

**Comment by cyrrill** [comment] 2016-09-09 04:49
Hard to tell with the markdown being rendered, but for sure it looks like a syntax error, as the message says "ERROR! Syntax Error while loading YAML."

Try pasting into here and see what the validation says:  http://www.yamllint.com/

Else, just overwrite with https://raw.githubusercontent.com/jlund/streisand/master/playbooks/roles/genesis-amazon/defaults/main.yml  and save, then try again

**Comment by gladiator26** [comment] 2016-09-09 20:40
You're the man. It's working now with t2.medium instance type. So, all works great unless I have to reboot the instance. Once rebooted, the status check fails 1/2 and the log shows "Failed to start Raise network interfaces."  I then terminate the instance a create a new install. I can live with this, but if there is a solution to this I would be very grateful. 

PS: I don't think it's related to elastic ips as this option is enabled and the IPs do not change upon reboot.


Thank you again

**Comment by danpodeanu** [comment] 2016-10-24 18:47
I can confirm that rebooting Streisand AWS instances from inside the instance (i.e. "sudo reboot") makes them refuse to start-- most likely the same behavior would be exhibited by any kind of restarts.

The error message from the instance console is:

[^[[0;32m  OK  ^[[0m] Started Initial cloud-init job (pre-networking).
[^[[0;32m  OK  ^[[0m] Reached target Network (Pre).
[^[[0;32m  OK  ^[[0m] Started ifup for eth0.
         Starting Raise network interfaces...
[^[[0;1;31mFAILED^[[0m] Failed to start Raise network interfaces.
See 'systemctl status networking.service' for details.
[^[[0;1;33mDEPEND^[[0m] Dependency failed for Initial cloud... job (metadata service crawler).

Still researching what went wrong.

**Comment by danpodeanu** [comment] 2016-10-25 11:50
This appears to be the bug specific to Ubuntu Xenial and OpenVPN:

https://bugs.launchpad.net/ubuntu/+source/openvpn/+bug/1580356
https://bugs.launchpad.net/ubuntu/+source/openvpn/+bug/1598522

Solved by making the following change:

sed -i -e 's/After=network.target/After=network.target network-online.target/' /lib/systemd/system/openvpn.service

**Comment by jlund** [comment] 2016-10-30 22:47
This should be fixed. Thanks for the pointers, @danpodeanu!

**Closed** 2016-11-01 07:30 UTC
