### ISSUE TITLE
"tor-bridge Reload the system_tor AppArmor profile for the override to take effect" is error

### ISSUE THREAD

**Issue by HougeLangley** [jlund/streisand#880] opened 2017-08-08 17:08 UTC
### Steps to Reproduce:
1. 

#### *Log output from Ansible or other relevant services (link to Gist for longer output):
TASK [tor-bridge : Reload the system_tor AppArmor profile for the override to take effect] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["apparmor_parser", "-r", "/etc/apparmor.d/system_tor"], "delta": "0:00:00.005799", "end": "2017-08-08 17:04:49.158690", "failed": true, "rc": 1, "start": "2017-08-08 17:04:49.152891", "stderr": "Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)\nWarning: unable to find a suitable fs in /proc/mounts, is it mounted?\nUse --subdomainfs to override.", "stderr_lines": ["Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)", "Warning: unable to find a suitable fs in /proc/mounts, is it mounted?", "Use --subdomainfs to override."], "stdout": "", "stdout_lines": []}

**Comment by HougeLangley** [comment] 2017-08-08 17:14
I have noticed that the kernel version used in Ubuntu 16.04 in Linode is 4.9. But in DigitalOcean is 4.4.

Some wrong with this ?

**Comment by HougeLangley** [comment] 2017-08-08 17:33
Using default version  of kernel could solved the problem.

https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm

**Comment by HougeLangley** [comment] 2017-08-08 18:27
Problem solved. DO NOT USED KERNEL VERSION THE LINODE PROVIDED !!!

**Comment by cpu** [comment] 2017-08-08 18:39
>  Problem solved. DO NOT USED KERNEL VERSION THE LINODE PROVIDED !!!

Did you create the Linode instance manually & then use Streisand to configure it in "existing server" or "localhost" mode? If so you've arrived at the right conclusion :-)

Streisand already [uses a monkey-patch to the Linode python module](https://github.com/jlund/streisand/blob/3ce4b8abd15c9fb12d0cc1a9c8dc1d5365e38c3f/monkey/usercustomize.py) to override the kernel to use a mainline kernel that works nicely with Wireguard. If you created the Linode instance through the `./streisand` script by giving it your Linode API key this problem shouldn't have happened and might indicate a bug.

**Comment by HougeLangley** [comment] 2017-08-08 18:52
@cpu Yes, I used localhost mode.

**Comment by cpu** [comment] 2017-08-08 18:55
@HougeLangley Great! thanks for clarifying. Happy to hear there isn't a bug to squash! :mag_right: :beetle:

**Comment by littlebtc** [comment] 2017-08-09 22:38
Bad news, I use `./streisand`, using Tokyo-2 and my own API key, then the error still pop up:

````
TASK [tor-bridge : Reload the system_tor AppArmor profile for the override to take effect] ************************************************************************************************************************
fatal: [139.162.90.78]: FAILED! => {"changed": true, "cmd": ["apparmor_parser", "-r", "/etc/apparmor.d/system_tor"], "delta": "0:00:00.005714", "end": "2017-08-09 22:37:02.223269", "failed": true, "rc": 1, "start": "2017-08-09 22:37:02.217555", "stderr": "Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)\nWarning: unable to find a suitable fs in /proc/mounts, is it mounted?\nUse --subdomainfs to override.", "stderr_lines": ["Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)", "Warning: unable to find a suitable fs in /proc/mounts, is it mounted?", "Use --subdomainfs to override."], "stdout": "", "stdout_lines": []}
````

As told by Linode Manager, the kernel selected by streisand is `Latest 64 bit (4.9.36-x86_64-linode85)`, which seems to build on July 17.

Time to open this issue again and fix that? :cry:

**Comment by cpu** [comment] 2017-09-09 01:46
@littlebtc I just tried a fresh Linode provision using master and Tokyo-2. I can't reproduce the error. Are you still able to?

**Comment by cpu** [comment] 2017-09-11 17:25
Closing this issue for now since I can't reproduce. Thanks!

**Closed by cpu** 2017-09-11 17:25 UTC
Labels: area/tor, kind/bug, provider/linode
