### ISSUE TITLE
[Feature Request] Provide SSTP support by adding Softether VPN

### ISSUE THREAD

**Issue by HowardMei** [jlund/streisand#722] opened 2017-06-02 08:47 UTC
Could you please add Softether VPN support as an option?
http://www.softether.org/
I'm not sure if it's conflicting with existing L2TP/OpenVPN setup,
so I'd better file a request.

**Comment by cpu** [comment] 2017-06-02 14:05
Hi @HowardMei - this is a duplicate of https://github.com/jlund/streisand/issues/140, so I'm going to close it. Thanks for the suggestion, please follow #140 for that discussion.

**Closed by cpu** 2017-06-02 14:05 UTC
