### ISSUE TITLE
Error cpu_threshold Installing on Linode Server.

### ISSUE THREAD

**Issue by ianbarton** [jlund/streisand#928] opened 2017-09-07 18:03 UTC
### Expected behavior:
I set up a new Linode instance running Ubuntu 16.04. I wanted streisand to create a new Linode instance and install on that.

### Actual Behavior:
The ansible script failed with:

TASK [genesis-linode : Create the server] ********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Alert_cpu_threshold must be between 0 and 2000."}
        to retry, use: --limit @/root/streisand/playbooks/linode.retry

Retried using command above. Got the same error. 

##### *Output from `git rev-parse HEAD` in your Streisand directory :*
    aa69d236dcbf48594a524da89969a95e7ff788de

**Comment by cpu** [comment] 2017-09-07 18:10
Hi @ianbarton,

Thanks for opening this issue. It looks like this is a duplicate of https://github.com/jlund/streisand/issues/626 so I'm going to close this one. Thanks for understanding.

Can you try [the workaround suggestedby @cmeid in #626](https://github.com/jlund/streisand/issues/626#issuecomment-319812261) and report back to that thread if it works? Thanks!

**Closed by cpu** 2017-09-07 18:10 UTC
